.TH "src/language Directory Reference" 3 "Thu Mar 28 2013" "Version v1.0" "Labris Wireless Access Point Controller" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/language Directory Reference \- 
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fB__init__\&.py\fP"
.br
.ti -1c
.RI "file \fBLanguage\&.py\fP"
.br
.in -1c
