.TH "src/controller/ConfigMethods.py" 3 "Tue Mar 26 2013" "Version v1.0" "Labris Wireless Access Point Controller" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/controller/ConfigMethods.py \- 
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBsrc\&.controller\&.ConfigMethods\&.ConfigMethods\fP"
.br
.RI "\fI\fBConfigMethods\fP class aims to provide required metdhos to requester class or methods to read, update Config object\&. \fP"
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBsrc\&.controller\&.ConfigMethods\fP"
.br
.ti -1c
.RI "namespace \fBcontroller\fP"
.br
.RI "\fICopyright 2013 Labris Technology\&. \fP"
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Labris Wireless Access Point Controller from the source code\&.
