.TH "ConsoleInterface" 3 "Tue Mar 26 2013" "Version v1.0" "Labris Wireless Access Point Controller" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ConsoleInterface \- 
.PP
Command list to implement all required methods pre-defined\&.  

.SH SYNOPSIS
.br
.PP
.SH "Detailed Description"
.PP 
Command list to implement all required methods pre-defined\&. 

inherited from cmd library to handle commandline interface with user interaction\&. This class gathers commands from user and declare them into individual methods written in project own classes\&.
.PP
\fBParameters:\fP
.RS 4
\fI\fP cmd\&.Cmd is a library object 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for Labris Wireless Access Point Controller from the source code\&.
