.TH "ConsoleInterface" 3 "Thu Mar 21 2013" "Version v1.0" "Labris Wireless Access Point Controller" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ConsoleInterface \- 
.PP
\fBMain\fP class handles main requires and distribute them into related subprocesses\&.  

.SH SYNOPSIS
.br
.PP
.SH "Detailed Description"
.PP 
\fBMain\fP class handles main requires and distribute them into related subprocesses\&. 

This class is called by with sub-controllers\&. \fBMain\fP class also manipulate commandline arguments, clear them from whitespaces, apply a filter regex and send them into 

.SH "Author"
.PP 
Generated automatically by Doxygen for Labris Wireless Access Point Controller from the source code\&.
