.TH "db" 3 "Tue Mar 26 2013" "Version v1.0" "Labris Wireless Access Point Controller" \" -*- nroff -*-
.ad l
.nh
.SH NAME
db \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBsrc\&.database\&.Database\&.Database\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Labris Wireless Access Point Controller from the source code\&.
