.TH "src/database/db.py" 3 "Thu Mar 21 2013" "Version v1.0" "Labris Wireless Access Point Controller" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/database/db.py \- 
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBsrc\&.database\&.db\&.Database\fP"
.br
.RI "\fI\fBDatabase\fP class implement a database interface between application and postgresql\&. \fP"
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBsrc\&.database\&.db\fP"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "string \fBsrc\&.database\&.db\&.__author__\fP = 'fatih'"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Labris Wireless Access Point Controller from the source code\&.
