.TH "src/controller/DeviceMethods.py" 3 "Thu May 2 2013" "Version v1.1.0" "Labris Wireless Access Point Controller" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/controller/DeviceMethods.py \- 
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBsrc\&.controller\&.DeviceMethods\&.DeviceMethods\fP"
.br
.RI "\fI\fBDeviceMethods\fP class includes device oriented methods such CRUD operations\&. \fP"
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBsrc\&.controller\&.DeviceMethods\fP"
.br
.ti -1c
.RI "namespace \fBcontroller\fP"
.br
.RI "\fICopyright 2013 Labris Technology\&. \fP"
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "string \fBsrc\&.controller\&.DeviceMethods\&.__author__\fP = 'fatih'"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Labris Wireless Access Point Controller from the source code\&.
