.TH "src/model/Device.py" 3 "Thu Apr 25 2013" "Version v1.1.0" "Labris Wireless Access Point Controller" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/model/Device.py \- 
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBsrc\&.model\&.Device\&.Device\fP"
.br
.RI "\fI\fBDevice\fP object class to create a runtime instance while adding a new device\&. \fP"
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBsrc\&.model\&.Device\fP"
.br
.ti -1c
.RI "namespace \fBmodel\fP"
.br
.RI "\fICopyright 2013 Labris Technology\&. \fP"
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Labris Wireless Access Point Controller from the source code\&.
