.TH "dict" 3 "Thu Apr 25 2013" "Version v1.1.0" "Labris Wireless Access Point Controller" \" -*- nroff -*-
.ad l
.nh
.SH NAME
dict \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBsrc\&.model\&.Config\&.Config\fP, \fBsrc\&.model\&.Config\&.Config\fP, and \fBsrc\&.model\&.Request\&.Request\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Labris Wireless Access Point Controller from the source code\&.
