.TH "src/helper/Formatter.py" 3 "Tue Mar 26 2013" "Version v1.0" "Labris Wireless Access Point Controller" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/helper/Formatter.py \- 
.SH SYNOPSIS
.br
.PP
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBsrc\&.helper\&.Formatter\fP"
.br
.ti -1c
.RI "namespace \fBhelper\fP"
.br
.RI "\fICopyright 2013 Labris Technology\&. \fP"
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "def \fBsrc\&.helper\&.Formatter\&.indent\fP"
.br
.RI "\fIIndents a table by column\&. \fP"
.ti -1c
.RI "def \fBsrc\&.helper\&.Formatter\&.wrap_onspace\fP"
.br
.RI "\fIA word-wrap function that preserves existing line breaks and most spaces in the text\&. \fP"
.ti -1c
.RI "def \fBsrc\&.helper\&.Formatter\&.wrap_onspace_strict\fP"
.br
.RI "\fISimilar to wrap_onspace, but enforces the width constraint: words longer than width are split\&. \fP"
.ti -1c
.RI "def \fBsrc\&.helper\&.Formatter\&.wrap_always\fP"
.br
.RI "\fIA simple word-wrap function that wraps text on exactly width characters\&. \fP"
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Labris Wireless Access Point Controller from the source code\&.
