.TH "src/helper/formatter.py" 3 "Thu Mar 21 2013" "Version v1.0" "Labris Wireless Access Point Controller" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/helper/formatter.py \- 
.SH SYNOPSIS
.br
.PP
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBsrc\&.helper\&.formatter\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "def \fBsrc\&.helper\&.formatter\&.indent\fP"
.br
.RI "\fIIndents a table by column\&. \fP"
.ti -1c
.RI "def \fBsrc\&.helper\&.formatter\&.wrap_onspace\fP"
.br
.RI "\fIA word-wrap function that preserves existing line breaks and most spaces in the text\&. \fP"
.ti -1c
.RI "def \fBsrc\&.helper\&.formatter\&.wrap_onspace_strict\fP"
.br
.RI "\fI:param text: :param width: Similar to wrap_onspace, but enforces the width constraint: words longer than width are split\&. \fP"
.ti -1c
.RI "def \fBsrc\&.helper\&.formatter\&.wrap_always\fP"
.br
.RI "\fIA simple word-wrap function that wraps text on exactly width characters\&. \fP"
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "tuple \fBsrc\&.helper\&.formatter\&.labels\fP = ('First Name', 'Last Name', 'Age', 'Position')"
.br
.ti -1c
.RI "\fBsrc\&.helper\&.formatter\&.data\fP = \\"
.br
.ti -1c
.RI "\fBlist\fP \fBsrc\&.helper\&.formatter\&.rows\fP = [row\&.strip()\&.split(',') for row in data\&.splitlines()]"
.br
.ti -1c
.RI "int \fBsrc\&.helper\&.formatter\&.width\fP = 30"
.br
.ti -1c
.RI "string \fBsrc\&.helper\&.formatter\&.prefix\fP = '| '"
.br
.ti -1c
.RI "tuple \fBsrc\&.helper\&.formatter\&.wrapfunc\fP = lambdax:wrapper(x, width)"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Labris Wireless Access Point Controller from the source code\&.
