.TH "src/controller/GroupMethods.py" 3 "Thu Apr 25 2013" "Version v1.1.0" "Labris Wireless Access Point Controller" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/controller/GroupMethods.py \- 
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBsrc\&.controller\&.GroupMethods\&.GroupMethods\fP"
.br
.RI "\fI\fBGroupMethods\fP class includes group oriented methods such group set, group unset, group show operations\&. \fP"
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBsrc\&.controller\&.GroupMethods\fP"
.br
.ti -1c
.RI "namespace \fBcontroller\fP"
.br
.RI "\fICopyright 2013 Labris Technology\&. \fP"
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Labris Wireless Access Point Controller from the source code\&.
