.TH "helper" 3 "Tue Mar 26 2013" "Version v1.0" "Labris Wireless Access Point Controller" \" -*- nroff -*-
.ad l
.nh
.SH NAME
helper \- 
.PP
Copyright 2013 Labris Technology\&.  

.SH SYNOPSIS
.br
.PP
.SH "Detailed Description"
.PP 
Copyright 2013 Labris Technology\&. 

Licensed under the Apache License, Version 2\&.0 (the 'License'); you may not use this file except in compliance with the License\&. You may obtain a copy of the License at
.PP
http://www.apache.org/licenses/LICENSE-2.0
.PP
Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an 'AS IS' BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied\&. See the License for the specific language governing permissions and limitations under the License\&.
.PP
\fBDate:\fP
.RS 4
Marh 13, 2013 
.RE
.PP
\fBAuthor:\fP
.RS 4
Fatih Karatana 
.PP
\fCfatih@karatana\&.com\fP 
.RE
.PP
\fBCopyright:\fP
.RS 4
Labris Technology
.RE
.PP
Licensed under the Apache License, Version 2\&.0 (the 'License'); you may not use this file except in compliance with the License\&. You may obtain a copy of the License at
.PP
http://www.apache.org/licenses/LICENSE-2.0
.PP
Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an 'AS IS' BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied\&. See the License for the specific language governing permissions and limitations under the License\&.
.PP
\fBDate:\fP
.RS 4
Marh 13, 2013 
.RE
.PP
\fBAuthor:\fP
.RS 4
Mike Brown http://aspn.activestate.com/ASPN/Cookbook/Python/Recipe/148061 
.PP
Fatih Karatana 
.RE
.PP
\fBCopyright:\fP
.RS 4
Labris Technology 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for Labris Wireless Access Point Controller from the source code\&.
