.TH "src/language/Language.py" 3 "Thu Mar 28 2013" "Version v1.0" "Labris Wireless Access Point Controller" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/language/Language.py \- 
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBsrc\&.language\&.Language\&.Language\fP"
.br
.RI "\fI\fBLanguage\fP class aims to provide required statement to requester class or methods to read matching locale string with given language code\&. \fP"
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBsrc\&.language\&.Language\fP"
.br
.ti -1c
.RI "namespace \fBlanguage\fP"
.br
.RI "\fICopyright 2013 Labris Technology\&. \fP"
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Labris Wireless Access Point Controller from the source code\&.
