.TH "src/model/Log.py" 3 "Thu May 2 2013" "Version v1.1.0" "Labris Wireless Access Point Controller" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/model/Log.py \- 
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBsrc\&.model\&.Log\&.Log\fP"
.br
.RI "\fI\fBLog\fP class is used to define log model data structure and\&. \fP"
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBsrc\&.model\&.Log\fP"
.br
.ti -1c
.RI "namespace \fBcli\fP"
.br
.RI "\fICopyright 2013 Labris Technology\&. \fP"
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "string \fBsrc\&.model\&.Log\&.__author__\fP = 'fatih'"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Labris Wireless Access Point Controller from the source code\&.
