.TH "Main" 3 "Thu Mar 28 2013" "Version v1.0" "Labris Wireless Access Point Controller" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Main \- 
.PP
Group set makes users to set handle group operations for set command\&.  

.SH SYNOPSIS
.br
.PP
.SH "Detailed Description"
.PP 
Group set makes users to set handle group operations for set command\&. 

.PP
.nf
     It can be done by user such as ssid, channel, associations, etc.

     Group set moderated by set by seperating type
     arguments such as group.

     Sample usage to reach this method is below:
     $ set -t group -o [OPTION] -i [id]
.fi
.PP
.PP
\fBParameters:\fP
.RS 4
\fIconfig\fP 
.br
\fIparams\fP 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for Labris Wireless Access Point Controller from the source code\&.
