.TH "Main" 3 "Thu May 2 2013" "Version v1.1.0" "Labris Wireless Access Point Controller" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Main \- 
.PP
Group set makes users to set handle group operations for set command\&.  

.SH SYNOPSIS
.br
.PP
.SH "Detailed Description"
.PP 
Group set makes users to set handle group operations for set command\&. 

It can be done by user such as ssid, channel, associations, etc\&.
.PP
Group set moderated by set by separating type arguments such as group\&.
.PP
Sample usage to reach this method is below: $ set -t group -o [OPTION] -i [id]
.PP
\fBParameters:\fP
.RS 4
\fIconfig\fP 
.br
\fIparams\fP 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for Labris Wireless Access Point Controller from the source code\&.
