.TH "object" 3 "Thu May 2 2013" "Version v1.1.0" "Labris Wireless Access Point Controller" \" -*- nroff -*-
.ad l
.nh
.SH NAME
object \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBsrc\&.cli\&.CommunicationInterface\&.CommunicationInterface\fP, \fBsrc\&.controller\&.GroupMethods\&.GroupMethods\fP, \fBsrc\&.controller\&.main\&.Main\fP, \fBsrc\&.database\&.CouchDriver\&.CouchDriver\fP, \fBsrc\&.database\&.Database\&.Database\fP, \fBsrc\&.database\&.PostgreDriver\&.PostgreDriver\fP, \fBsrc\&.helpers\&.ArgParser\&.ArgParser\fP, \fBsrc\&.helpers\&.Utils\&.Utils\fP, \fBsrc\&.language\&.Language\&.Language\fP, \fBsrc\&.model\&.VLan\&.VLan\fP, \fBsrc\&.resources\&.Resources\&.Resources\fP, and \fBsrc\&.resources\&.SQL\&.SQL\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Labris Wireless Access Point Controller from the source code\&.
