.TH "src/database/PostgreDriver.py" 3 "Thu Apr 25 2013" "Version v1.1.0" "Labris Wireless Access Point Controller" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/database/PostgreDriver.py \- 
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBsrc\&.database\&.PostgreDriver\&.PostgreDriver\fP"
.br
.RI "\fI\fBPostgreDriver\fP class implement a database interface between application database class and postgresql\&. \fP"
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBsrc\&.database\&.PostgreDriver\fP"
.br
.ti -1c
.RI "namespace \fBdatabase\fP"
.br
.RI "\fICopyright 2013 Labris Technology\&. \fP"
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "string \fBsrc\&.database\&.PostgreDriver\&.__author__\fP = 'fatih'"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Labris Wireless Access Point Controller from the source code\&.
