.TH "src/model/Request.py" 3 "Thu May 2 2013" "Version v1.1.0" "Labris Wireless Access Point Controller" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/model/Request.py \- 
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBsrc\&.model\&.Request\&.Request\fP"
.br
.RI "\fI\fBRequest\fP object class to generate a new request 'enable':true, 'configure':false, 'commands':[ { 'command':'showa dot11 bssid' } ]\&. \fP"
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBsrc\&.model\&.Request\fP"
.br
.ti -1c
.RI "namespace \fBmodel\fP"
.br
.RI "\fICopyright 2013 Labris Technology\&. \fP"
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Labris Wireless Access Point Controller from the source code\&.
