.TH "src/resources/resources.py" 3 "Thu Mar 21 2013" "Version v1.0" "Labris Wireless Access Point Controller" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/resources/resources.py \- 
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBsrc\&.resources\&.resources\&.Resources\fP"
.br
.RI "\fI\fBResources\fP file covers all required global variables, pathnames, filenames, etc\&. \fP"
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBsrc\&.resources\&.resources\fP"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "string \fBsrc\&.resources\&.resources\&.__author__\fP = 'fatih'"
.br
.ti -1c
.RI "string \fBsrc\&.resources\&.resources\&.__date__\fP = '$Jan 22, 2013 11:08:40 AM$'"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Labris Wireless Access Point Controller from the source code\&.
