.TH "src/resources/SQL.py" 3 "Tue Mar 26 2013" "Version v1.0" "Labris Wireless Access Point Controller" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/resources/SQL.py \- 
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBsrc\&.resources\&.SQL\&.SQL\fP"
.br
.RI "\fIThis class includes all using database commands such as insert, remove, select etc\&. \fP"
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBsrc\&.resources\&.SQL\fP"
.br
.ti -1c
.RI "namespace \fBconfig\fP"
.br
.RI "\fICopyright 2013 Labris Technology\&. \fP"
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Labris Wireless Access Point Controller from the source code\&.
