.TH "src.database.db.Database" 3 "Thu Mar 21 2013" "Version v1.0" "Labris Wireless Access Point Controller" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src.database.db.Database \- 
.PP
\fBDatabase\fP class implement a database interface between application and postgresql\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBobject\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "def \fB__init__\fP"
.br
.ti -1c
.RI "def \fBconnect\fP"
.br
.RI "\fI.PP
.nf
Connect database with given parameters
.fi
.PP
 :rtype : object \fP"
.ti -1c
.RI "def \fBselect\fP"
.br
.RI "\fI.PP
.nf
Remove objects from given tables
.fi
.PP
 :param cmd: \fP"
.ti -1c
.RI "def \fBinsert\fP"
.br
.RI "\fI.PP
.nf
Insert objects to database
expected json formats for inserting objects
.fi
.PP
 :param cmd: \fP"
.ti -1c
.RI "def \fBupdate\fP"
.br
.RI "\fI.PP
.nf
Update database objects with given values
.fi
.PP
 :param cmd: \fP"
.ti -1c
.RI "def \fBremove\fP"
.br
.RI "\fI.PP
.nf
Remove objects from given tables
.fi
.PP
 :param cmd: \fP"
.ti -1c
.RI "def \fBclose_conn\fP"
.br
.RI "\fI:param con: \fP"
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fButils\fP"
.br
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "\fB__config__\fP"
.br
.ti -1c
.RI "\fB__section__\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
\fBDatabase\fP class implement a database interface between application and postgresql\&. 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "def src\&.database\&.db\&.Database\&.__init__ (self)"

.SH "Member Function Documentation"
.PP 
.SS "def src\&.database\&.db\&.Database\&.close_conn (self, con)"

.PP
:param con: 
.SS "def src\&.database\&.db\&.Database\&.connect (self)"

.PP
.PP
.nf
Connect database with given parameters
.fi
.PP
 :rtype : object 
.SS "def src\&.database\&.db\&.Database\&.insert (self, cmd)"

.PP
.PP
.nf
Insert objects to database
expected json formats for inserting objects
.fi
.PP
 :param cmd: 
.SS "def src\&.database\&.db\&.Database\&.remove (self, cmd)"

.PP
.PP
.nf
Remove objects from given tables
.fi
.PP
 :param cmd: 
.SS "def src\&.database\&.db\&.Database\&.select (self, cmd)"

.PP
.PP
.nf
Remove objects from given tables
.fi
.PP
 :param cmd: 
.SS "def src\&.database\&.db\&.Database\&.update (self, cmd)"

.PP
.PP
.nf
Update database objects with given values
.fi
.PP
 :param cmd: 
.SH "Member Data Documentation"
.PP 
.SS "src\&.database\&.db\&.Database\&.__config__\fC [private]\fP"

.SS "src\&.database\&.db\&.Database\&.__section__\fC [private]\fP"

.SS "src\&.database\&.db\&.Database\&.utils"


.SH "Author"
.PP 
Generated automatically by Doxygen for Labris Wireless Access Point Controller from the source code\&.
