.TH "src.model.Config.Config" 3 "Thu May 2 2013" "Version v1.1.0" "Labris Wireless Access Point Controller" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src.model.Config.Config \- 
.PP
\fBDevice\fP configuration model to implement new instance while inserting a new device\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBdict\fP, and \fBdict\fP\&.
.PP
Inherited by \fBsrc\&.model\&.Device\&.Device\fP, and \fBsrc\&.model\&.Device\&.Device\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "def \fB__init__\fP"
.br
.RI "\fIConstructor for \fBConfig\fP model\&. \fP"
.ti -1c
.RI "def \fBset_id\fP"
.br
.RI "\fISetter for id variable\&. \fP"
.ti -1c
.RI "def \fBget_id\fP"
.br
.RI "\fIGetter for instance id\&. \fP"
.ti -1c
.RI "def \fBset_name\fP"
.br
.RI "\fISetter for name variable\&. \fP"
.ti -1c
.RI "def \fBget_name\fP"
.br
.RI "\fIGetter for name variable\&. \fP"
.ti -1c
.RI "def \fBset_description\fP"
.br
.RI "\fISetter for \fBConfig\fP description\&. \fP"
.ti -1c
.RI "def \fBget_description\fP"
.br
.RI "\fIGetter for description\&. \fP"
.ti -1c
.RI "def \fBset_ip\fP"
.br
.RI "\fISetter for ip\&. \fP"
.ti -1c
.RI "def \fBget_ip\fP"
.br
.RI "\fIGetter for ip variable return\&. \fP"
.ti -1c
.RI "def \fBset_username\fP"
.br
.RI "\fIThis username variable is set to define connection parameters for given device\&. \fP"
.ti -1c
.RI "def \fBget_username\fP"
.br
.ti -1c
.RI "def \fBset_password\fP"
.br
.RI "\fIThis password variable is set to define connection parameters for given device\&. \fP"
.ti -1c
.RI "def \fBget_password\fP"
.br
.ti -1c
.RI "def \fBset_enable_password\fP"
.br
.RI "\fIThis variable is set to define enable connection parameters for given device\&. \fP"
.ti -1c
.RI "def \fBget_enable_password\fP"
.br
.RI "\fIGetter for enable password variable\&. \fP"
.ti -1c
.RI "def \fBset_radius\fP"
.br
.RI "\fISetter for radius configuration id for recent \fBConfig\fP instance\&. \fP"
.ti -1c
.RI "def \fBget_radius\fP"
.br
.RI "\fIGet radius variable\&. \fP"
.ti -1c
.RI "def \fBset_ssid\fP"
.br
.RI "\fISetter for ssid variable\&. \fP"
.ti -1c
.RI "def \fBget_ssid\fP"
.br
.RI "\fIGetter for ssid\&. \fP"
.ti -1c
.RI "def \fBset_vlan\fP"
.br
.RI "\fISetter for vlan variable\&. \fP"
.ti -1c
.RI "def \fBget_vlan\fP"
.br
.RI "\fIGetter for vlan\&. \fP"
.ti -1c
.RI "def \fBset_channel\fP"
.br
.RI "\fISetter for channel\&. \fP"
.ti -1c
.RI "def \fBget_channel\fP"
.br
.RI "\fIGetter for channel variables\&. \fP"
.ti -1c
.RI "def \fBset_transport_protocol\fP"
.br
.RI "\fISetter for transport protocol\&. \fP"
.ti -1c
.RI "def \fBget_transport_protocol\fP"
.br
.RI "\fIGetter for transport protocol\&. \fP"
.ti -1c
.RI "def \fBset_personality\fP"
.br
.RI "\fISetter for personality\&. \fP"
.ti -1c
.RI "def \fBget_personality\fP"
.br
.RI "\fIGetter for personality\&. \fP"
.ti -1c
.RI "def \fBset_maxclient\fP"
.br
.RI "\fISetter for maxclient\&. \fP"
.ti -1c
.RI "def \fBget_maxclient\fP"
.br
.RI "\fIGetter for maxclient variable\&. \fP"
.ti -1c
.RI "def \fBset_request\fP"
.br
.RI "\fISet request\&. \fP"
.ti -1c
.RI "def \fBget_request\fP"
.br
.RI "\fIGetter for \fBRequest\fP model\&. \fP"
.ti -1c
.RI "def \fBset_date_add\fP"
.br
.RI "\fISet add date of recent \fBConfig\fP instance\&. \fP"
.ti -1c
.RI "def \fBget_date_add\fP"
.br
.RI "\fIAdd date of \fBConfig\fP instance\&. \fP"
.ti -1c
.RI "def \fBset_date_modified\fP"
.br
.RI "\fISet last modified date for recent instance\&. \fP"
.ti -1c
.RI "def \fBget_date_modified\fP"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "def \fB__init__\fP"
.br
.RI "\fIConstructor for \fBDevice\fP model\&. \fP"
.ti -1c
.RI "def \fBset_id\fP"
.br
.RI "\fISetter for id variable is a private method\&. \fP"
.ti -1c
.RI "def \fBget_id\fP"
.br
.RI "\fIGetter for instance device ipcut\&. \fP"
.ti -1c
.RI "def \fBset_ip\fP"
.br
.RI "\fISetter for id variable is a private method\&. \fP"
.ti -1c
.RI "def \fBget_ip\fP"
.br
.RI "\fIGetter for instance device id\&. \fP"
.ti -1c
.RI "def \fBset_device_brand\fP"
.br
.RI "\fISetter for brand variable\&. \fP"
.ti -1c
.RI "def \fBget_brand\fP"
.br
.RI "\fIGetter for brand variable\&. \fP"
.ti -1c
.RI "def \fBset_model\fP"
.br
.RI "\fISetter for model variable\&. \fP"
.ti -1c
.RI "def \fBget_model\fP"
.br
.RI "\fIGetter for model\&. \fP"
.ti -1c
.RI "def \fBset_firmware\fP"
.br
.RI "\fISetter for \fBDevice\fP firmware variable\&. \fP"
.ti -1c
.RI "def \fBget_firmware\fP"
.br
.RI "\fIGetter for firmware\&. \fP"
.ti -1c
.RI "def \fBset_relation\fP"
.br
.RI "\fISetter for relation variable\&. \fP"
.ti -1c
.RI "def \fBget_relation\fP"
.br
.RI "\fIGetter for relation variable\&. \fP"
.ti -1c
.RI "def \fBset_name\fP"
.br
.RI "\fISetter for name parameter\&. \fP"
.ti -1c
.RI "def \fBget_name\fP"
.br
.RI "\fIGetter for name variable\&. \fP"
.ti -1c
.RI "def \fBset_description\fP"
.br
.RI "\fISetter for description variable to describe device in detail\&. \fP"
.ti -1c
.RI "def \fBget_description\fP"
.br
.RI "\fIGetter for description\&. \fP"
.ti -1c
.RI "def \fBset_config_id\fP"
.br
.RI "\fISetter for config_id\&. \fP"
.ti -1c
.RI "def \fBget_config_id\fP"
.br
.ti -1c
.RI "def \fBset_config\fP"
.br
.RI "\fISetter to set a \fBConfig\fP model into device instance config\&. \fP"
.ti -1c
.RI "def \fBget_config\fP"
.br
.RI "\fIGetter for \fBDevice\fP model to get instance \fBConfig\fP\&. \fP"
.in -1c