.TH "src.model.Config.Config" 3 "Thu Mar 21 2013" "Version v1.0" "Labris Wireless Access Point Controller" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src.model.Config.Config \- 
.PP
\fBDevice\fP configuration model to implement new instance while inserting a new device\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBdict\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "def \fB__init__\fP"
.br
.ti -1c
.RI "def \fBset_id\fP"
.br
.RI "\fI:param cID: \fP"
.ti -1c
.RI "def \fBget_id\fP"
.br
.RI "\fI:return: \fP"
.ti -1c
.RI "def \fBset_name\fP"
.br
.RI "\fI:param name: \fP"
.ti -1c
.RI "def \fBget_name\fP"
.br
.RI "\fI:return: \fP"
.ti -1c
.RI "def \fBset_description\fP"
.br
.RI "\fI:param self: :param description: \fP"
.ti -1c
.RI "def \fBget_description\fP"
.br
.RI "\fI:return: \fP"
.ti -1c
.RI "def \fBset_ip\fP"
.br
.RI "\fI:param ip: \fP"
.ti -1c
.RI "def \fBget_ip\fP"
.br
.RI "\fI:return: \fP"
.ti -1c
.RI "def \fBset_username\fP"
.br
.RI "\fI:param username: \fP"
.ti -1c
.RI "def \fBget_username\fP"
.br
.RI "\fI:return: \fP"
.ti -1c
.RI "def \fBset_password\fP"
.br
.RI "\fI:param password: \fP"
.ti -1c
.RI "def \fBget_password\fP"
.br
.RI "\fI:return: \fP"
.ti -1c
.RI "def \fBset_enable_password\fP"
.br
.RI "\fI:param option: \fP"
.ti -1c
.RI "def \fBget_enable_password\fP"
.br
.RI "\fI:return: \fP"
.ti -1c
.RI "def \fBset_radius\fP"
.br
.RI "\fI:param radius_config_id: \fP"
.ti -1c
.RI "def \fBget_radius\fP"
.br
.RI "\fI:return: \fP"
.ti -1c
.RI "def \fBset_ssid\fP"
.br
.RI "\fI:param ssid: \fP"
.ti -1c
.RI "def \fBget_ssid\fP"
.br
.RI "\fI:return: \fP"
.ti -1c
.RI "def \fBset_vlan\fP"
.br
.RI "\fI:param vlan_id: \fP"
.ti -1c
.RI "def \fBget_vlan\fP"
.br
.RI "\fI:return: \fP"
.ti -1c
.RI "def \fBset_channel\fP"
.br
.RI "\fI:param channel: \fP"
.ti -1c
.RI "def \fBget_channel\fP"
.br
.RI "\fI:return: \fP"
.ti -1c
.RI "def \fBset_transport_protocol\fP"
.br
.RI "\fI:param protocol: \fP"
.ti -1c
.RI "def \fBget_transport_protocol\fP"
.br
.RI "\fI:return: \fP"
.ti -1c
.RI "def \fBset_personality\fP"
.br
.RI "\fI:param personality: \fP"
.ti -1c
.RI "def \fBget_personality\fP"
.br
.RI "\fI:return personality: \fP"
.ti -1c
.RI "def \fBset_maxclient\fP"
.br
.RI "\fI.PP
.nf
Set request
.fi
.PP
 :param request: \fP"
.ti -1c
.RI "def \fBget_maxclient\fP"
.br
.RI "\fI:return: \fP"
.ti -1c
.RI "def \fBset_request\fP"
.br
.RI "\fI.PP
.nf
Set request
.fi
.PP
 :param request: \fP"
.ti -1c
.RI "def \fBget_request\fP"
.br
.RI "\fI:return: \fP"
.ti -1c
.RI "def \fBget_date_add\fP"
.br
.RI "\fI:return: \fP"
.ti -1c
.RI "def \fBset_date_modified\fP"
.br
.RI "\fI:param date: \fP"
.ti -1c
.RI "def \fBget_date_modified\fP"
.br
.RI "\fI:return: \fP"
.in -1c
.SH "Detailed Description"
.PP 
\fBDevice\fP configuration model to implement new instance while inserting a new device\&. 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "def src\&.model\&.Config\&.Config\&.__init__ (self)"

.SH "Member Function Documentation"
.PP 
.SS "def src\&.model\&.Config\&.Config\&.get_channel (self)"

.PP
:return: 
.SS "def src\&.model\&.Config\&.Config\&.get_date_add (self)"

.PP
:return: 
.SS "def src\&.model\&.Config\&.Config\&.get_date_modified (self)"

.PP
:return: 
.SS "def src\&.model\&.Config\&.Config\&.get_description (self)"

.PP
:return: 
.SS "def src\&.model\&.Config\&.Config\&.get_enable_password (self)"

.PP
:return: 
.SS "def src\&.model\&.Config\&.Config\&.get_id (self)"

.PP
:return: 
.SS "def src\&.model\&.Config\&.Config\&.get_ip (self)"

.PP
:return: 
.SS "def src\&.model\&.Config\&.Config\&.get_maxclient (self)"

.PP
:return: 
.SS "def src\&.model\&.Config\&.Config\&.get_name (self)"

.PP
:return: 
.SS "def src\&.model\&.Config\&.Config\&.get_password (self)"

.PP
:return: 
.SS "def src\&.model\&.Config\&.Config\&.get_personality (self)"

.PP
:return personality: 
.SS "def src\&.model\&.Config\&.Config\&.get_radius (self)"

.PP
:return: 
.SS "def src\&.model\&.Config\&.Config\&.get_request (self)"

.PP
:return: :param date: 
.SS "def src\&.model\&.Config\&.Config\&.get_ssid (self)"

.PP
:return: 
.SS "def src\&.model\&.Config\&.Config\&.get_transport_protocol (self)"

.PP
:return: 
.SS "def src\&.model\&.Config\&.Config\&.get_username (self)"

.PP
:return: 
.SS "def src\&.model\&.Config\&.Config\&.get_vlan (self)"

.PP
:return: 
.SS "def src\&.model\&.Config\&.Config\&.set_channel (self, channel)"

.PP
:param channel: 
.SS "def src\&.model\&.Config\&.Config\&.set_date_modified (self, date)"

.PP
:param date: 
.SS "def src\&.model\&.Config\&.Config\&.set_description (self, description)"

.PP
:param self: :param description: 
.SS "def src\&.model\&.Config\&.Config\&.set_enable_password (self, option)"

.PP
:param option: 
.SS "def src\&.model\&.Config\&.Config\&.set_id (self, cID)"

.PP
:param cID: 
.SS "def src\&.model\&.Config\&.Config\&.set_ip (self, ip)"

.PP
:param ip: 
.SS "def src\&.model\&.Config\&.Config\&.set_maxclient (self, request)"

.PP
.PP
.nf
Set request
.fi
.PP
 :param request: 
.SS "def src\&.model\&.Config\&.Config\&.set_name (self, name)"

.PP
:param name: 
.SS "def src\&.model\&.Config\&.Config\&.set_password (self, password)"

.PP
:param password: 
.SS "def src\&.model\&.Config\&.Config\&.set_personality (self, personality)"

.PP
:param personality: 
.SS "def src\&.model\&.Config\&.Config\&.set_radius (self, radius_config_id)"

.PP
:param radius_config_id: 
.SS "def src\&.model\&.Config\&.Config\&.set_request (self, request)"

.PP
.PP
.nf
Set request
.fi
.PP
 :param request: 
.SS "def src\&.model\&.Config\&.Config\&.set_ssid (self, ssid)"

.PP
:param ssid: 
.SS "def src\&.model\&.Config\&.Config\&.set_transport_protocol (self, protocol)"

.PP
:param protocol: 
.SS "def src\&.model\&.Config\&.Config\&.set_username (self, username)"

.PP
:param username: 
.SS "def src\&.model\&.Config\&.Config\&.set_vlan (self, vlan_id)"

.PP
:param vlan_id: 

.SH "Author"
.PP 
Generated automatically by Doxygen for Labris Wireless Access Point Controller from the source code\&.
