.TH "src.config.__sql__" 3 "Thu Mar 21 2013" "Version v1.0" "Labris Wireless Access Point Controller" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src.config.__sql__ \- 
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBSQL\fP"
.br
.RI "\fIThis class includes all using database commands such as insert, remove, select etc\&. \fP"
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "string \fB__author__\fP = 'fatih'"
.br
.RI "\fI\fBSQL\fP object covers all sql scripts\&. \fP"
.in -1c
.SH "Variable Documentation"
.PP 
.SS "string src\&.config\&.__sql__\&.__author__ = 'fatih'"

.PP
\fBSQL\fP object covers all sql scripts\&. 
.SH "Author"
.PP 
Generated automatically by Doxygen for Labris Wireless Access Point Controller from the source code\&.
