.TH "src.helper.Utils.Utils" 3 "Tue Mar 26 2013" "Version v1.0" "Labris Wireless Access Point Controller" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src.helper.Utils.Utils \- 
.PP
\fBUtils\fP class implements utility methods to help core methods work fine, independent, reliable and effective\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBobject\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "def \fBget_clean_params\fP"
.br
.RI "\fIget_clean_params method return filtered and processed arguments gathered from command line into argument parser\&. \fP"
.ti -1c
.RI "def \fBformatter\fP"
.br
.RI "\fIFormat output text as a human readable style\&. \fP"
.ti -1c
.RI "def \fBget_line\fP"
.br
.RI "\fIGet current line of file to handle exception lines\&. \fP"
.ti -1c
.RI "def \fBvalidate\fP"
.br
.RI "\fIThis method is used to validate given input source by type format such as IP, email, whitespace-fress strings, etc\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 
\fBUtils\fP class implements utility methods to help core methods work fine, independent, reliable and effective\&. 
.SH "Member Function Documentation"
.PP 
.SS "def src\&.helper\&.Utils\&.Utils\&.formatter (cls, heading, source)"

.PP
Format output text as a human readable style\&. \fBParameters:\fP
.RS 4
\fIcls\fP is class itself 
.br
\fIheading\fP is a list object comes from other methods to create a pretty table to be printed
.br
\fIsource\fP is a tuple list aims to create pretty table rows 
.RE
.PP

.SS "def src\&.helper\&.Utils\&.Utils\&.get_clean_params (cls, args)"

.PP
get_clean_params method return filtered and processed arguments gathered from command line into argument parser\&. .PP
.nf
     Arguments retreived with whitespaces, irregular order and mapped.
     Therefore it is need to be cleaned, reorganized and regularly mapped to
     send correct values into argument parser. This method help us to clean
     and get actual ordered parameters as a list.
.fi
.PP
.PP
\fBParameters:\fP
.RS 4
\fIcls\fP class itself 
.br
\fIargs\fP arguments list gathered from command line 
.RE
.PP
\fBReturns:\fP
.RS 4
A fully organized and clean argument list 
.RE
.PP

.SS "def src\&.helper\&.Utils\&.Utils\&.get_line (cls)"

.PP
Get current line of file to handle exception lines\&. \fBParameters:\fP
.RS 4
\fIcls\fP class itself
.RE
.PP
\fBReturns:\fP
.RS 4
Current number of line where method is called 
.RE
.PP

.SS "def src\&.helper\&.Utils\&.Utils\&.validate (cls, source = \fCNone\fP, stype = \fCNone\fP)"

.PP
This method is used to validate given input source by type format such as IP, email, whitespace-fress strings, etc\&. \fBParameters:\fP
.RS 4
\fIcls\fP class itself
.br
\fIstype\fP type defines what sort of value will be validated\&. Recently supported keys name, eth & ip
.br
\fIsource\fP 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for Labris Wireless Access Point Controller from the source code\&.
