.TH "src.cli.ConsoleInterface" 3 "Thu Mar 21 2013" "Version v1.0" "Labris Wireless Access Point Controller" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src.cli.ConsoleInterface \- 
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBConsoleInterface\fP"
.br
.RI "\fICommand list to implement all required methods pre-defined\&. \fP"
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Labris Wireless Access Point Controller from the source code\&.
