.TH "src.model.Commands.Commands" 3 "Thu May 2 2013" "Version v1.1.0" "Labris Wireless Access Point Controller" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src.model.Commands.Commands \- 
.PP
\fBCommands\fP object defines a \fBCommands\fP\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits list\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "def \fB__init__\fP"
.br
.RI "\fIConstructor of \fBCommands\fP model\&. \fP"
.ti -1c
.RI "def \fBset_command\fP"
.br
.RI "\fISetter to set a command belong this model\&. \fP"
.ti -1c
.RI "def \fBget_command\fP"
.br
.RI "\fIGetter for \fBCommands\fP model\&. \fP"
.ti -1c
.RI "def \fBset_param\fP"
.br
.RI "\fISetter for related param belong to any command\&. \fP"
.ti -1c
.RI "def \fBget_param\fP"
.br
.RI "\fIGetter for param\&. \fP"
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBcommand\fP"
.br
.ti -1c
.RI "\fBparam\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
\fBCommands\fP object defines a \fBCommands\fP\&. 

\fBCommands\fP object defines a \fBCommands\fP model to gather command related with given arguments from a pre-defined commands list in a JSON file and map them into \fBCommands\fP model\&. 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "def src\&.model\&.Commands\&.Commands\&.__init__ (self)"

.PP
Constructor of \fBCommands\fP model\&. 
.SH "Member Function Documentation"
.PP 
.SS "def src\&.model\&.Commands\&.Commands\&.get_command (self)"

.PP
Getter for \fBCommands\fP model\&. \fBReturns:\fP
.RS 4
command 
.RE
.PP

.SS "def src\&.model\&.Commands\&.Commands\&.get_param (self)"

.PP
Getter for param\&. \fBReturns:\fP
.RS 4
related param 
.RE
.PP

.SS "def src\&.model\&.Commands\&.Commands\&.set_command (self, command)"

.PP
Setter to set a command belong this model\&. \fBParameters:\fP
.RS 4
\fIcommand\fP 
.RE
.PP

.SS "def src\&.model\&.Commands\&.Commands\&.set_param (self, param)"

.PP
Setter for related param belong to any command\&. \fBParameters:\fP
.RS 4
\fIparam\fP 
.RE
.PP

.SH "Member Data Documentation"
.PP 
.SS "src\&.model\&.Commands\&.Commands\&.command"

.SS "src\&.model\&.Commands\&.Commands\&.param"


.SH "Author"
.PP 
Generated automatically by Doxygen for Labris Wireless Access Point Controller from the source code\&.
