.TH "src.resources.Resources.Resources" 3 "Tue Mar 26 2013" "Version v1.0" "Labris Wireless Access Point Controller" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src.resources.Resources.Resources \- 
.PP
\fBResources\fP file covers all required global variables, pathnames, filenames, etc\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBobject\fP\&.
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "string \fBROOT_PATH\fP = '/opt/labris/sbin/wapc/'"
.br
.ti -1c
.RI "string \fBSOURCE_PATH\fP = \fBROOT_PATH\fP+'src/'"
.br
.ti -1c
.RI "string \fBINCLUDE_PATH\fP = \fBSOURCE_PATH\fP+'include/'"
.br
.ti -1c
.RI "string \fBCONFIG_PATH\fP = \fBSOURCE_PATH\fP+'config/'"
.br
.ti -1c
.RI "string \fBBACKUP_PATH\fP = \fBSOURCE_PATH\fP+'backup/'"
.br
.ti -1c
.RI "string \fBci_script\fP = \fBINCLUDE_PATH\fP+'labris-wap-controller\&.pl'"
.br
.ti -1c
.RI "string \fBci_source\fP = \fBINCLUDE_PATH\fP+'input\&.json'"
.br
.ti -1c
.RI "string \fBinput_source\fP = \fBINCLUDE_PATH\fP+'%(file)s\&.json'"
.br
.ti -1c
.RI "string \fBci_config\fP = \fBINCLUDE_PATH\fP+'default\&.json'"
.br
.ti -1c
.RI "string \fBdevice_initial_config\fP = \fBCONFIG_PATH\fP+'%(path)s/%(relation)s-config\&.conf'"
.br
.ti -1c
.RI "string \fBdevice_load_command\fP = \fBINCLUDE_PATH\fP+'load\&.json'"
.br
.ti -1c
.RI "string \fBdevice_tftp_file\fP = '%(relation)s-config\&.conf'"
.br
.ti -1c
.RI "string \fBdevice_tftp_path\fP = '/var/tftpboot/'"
.br
.ti -1c
.RI "string \fBcfg_device_resource\fP = \fBCONFIG_PATH\fP+'wapc_config\&.json'"
.br
.ti -1c
.RI "string \fBback_name\fP = 'backup-{0}\&.bak'"
.br
.ti -1c
.RI "string \fBprompt\fP = 'WAPC:~ cli$ '"
.br
.ti -1c
.RI "string \fBtime_format\fP = '%Y-%m-%d %H:%M:%S'"
.br
.ti -1c
.RI "string \fBcfg_section_postgre\fP = 'postgre'"
.br
.ti -1c
.RI "string \fBcfg_section_mysql\fP = 'mysql'"
.br
.ti -1c
.RI "tuple \fBREGEX\fP"
.br
.in -1c
.SS "Static Private Attributes"

.in +1c
.ti -1c
.RI "string \fB__db__config__\fP = \fBCONFIG_PATH\fP+'database\&.cfg'"
.br
.in -1c
.SH "Detailed Description"
.PP 
\fBResources\fP file covers all required global variables, pathnames, filenames, etc\&. 

You need to configure only this file anytime you need to change variables 
.SH "Member Data Documentation"
.PP 
.SS "string src\&.resources\&.Resources\&.Resources\&.__db__config__ = \fBCONFIG_PATH\fP+'database\&.cfg'\fC [static]\fP, \fC [private]\fP"

.SS "string src\&.resources\&.Resources\&.Resources\&.back_name = 'backup-{0}\&.bak'\fC [static]\fP"

.SS "string src\&.resources\&.Resources\&.Resources\&.BACKUP_PATH = \fBSOURCE_PATH\fP+'backup/'\fC [static]\fP"

.SS "string src\&.resources\&.Resources\&.Resources\&.cfg_device_resource = \fBCONFIG_PATH\fP+'wapc_config\&.json'\fC [static]\fP"

.SS "string src\&.resources\&.Resources\&.Resources\&.cfg_section_mysql = 'mysql'\fC [static]\fP"

.SS "string src\&.resources\&.Resources\&.Resources\&.cfg_section_postgre = 'postgre'\fC [static]\fP"

.SS "string src\&.resources\&.Resources\&.Resources\&.ci_config = \fBINCLUDE_PATH\fP+'default\&.json'\fC [static]\fP"

.SS "string src\&.resources\&.Resources\&.Resources\&.ci_script = \fBINCLUDE_PATH\fP+'labris-wap-controller\&.pl'\fC [static]\fP"

.SS "string src\&.resources\&.Resources\&.Resources\&.ci_source = \fBINCLUDE_PATH\fP+'input\&.json'\fC [static]\fP"

.SS "string src\&.resources\&.Resources\&.Resources\&.CONFIG_PATH = \fBSOURCE_PATH\fP+'config/'\fC [static]\fP"

.SS "string src\&.resources\&.Resources\&.Resources\&.device_initial_config = \fBCONFIG_PATH\fP+'%(path)s/%(relation)s-config\&.conf'\fC [static]\fP"

.SS "string src\&.resources\&.Resources\&.Resources\&.device_load_command = \fBINCLUDE_PATH\fP+'load\&.json'\fC [static]\fP"

.SS "string src\&.resources\&.Resources\&.Resources\&.device_tftp_file = '%(relation)s-config\&.conf'\fC [static]\fP"

.SS "string src\&.resources\&.Resources\&.Resources\&.device_tftp_path = '/var/tftpboot/'\fC [static]\fP"

.SS "string src\&.resources\&.Resources\&.Resources\&.INCLUDE_PATH = \fBSOURCE_PATH\fP+'include/'\fC [static]\fP"

.SS "string src\&.resources\&.Resources\&.Resources\&.input_source = \fBINCLUDE_PATH\fP+'%(file)s\&.json'\fC [static]\fP"

.SS "string src\&.resources\&.Resources\&.Resources\&.prompt = 'WAPC:~ cli$ '\fC [static]\fP"

.SS "tuple src\&.resources\&.Resources\&.Resources\&.REGEX\fC [static]\fP"
\fBInitial value:\fP
.PP
.nf
1 = dict(name='^[a-zA-Z0-9]+$',
2                  ip='^(?:(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\\\&.)'
3                     '{3}(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)$',
4                  eth='^(\\w){1,6}[0-9]{1,3}([:\&.][0-9]{1,3})?$')
.fi
.SS "string src\&.resources\&.Resources\&.Resources\&.ROOT_PATH = '/opt/labris/sbin/wapc/'\fC [static]\fP"

.SS "string src\&.resources\&.Resources\&.Resources\&.SOURCE_PATH = \fBROOT_PATH\fP+'src/'\fC [static]\fP"

.SS "string src\&.resources\&.Resources\&.Resources\&.time_format = '%Y-%m-%d %H:%M:%S'\fC [static]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for Labris Wireless Access Point Controller from the source code\&.
