.TH "src.controller.GroupMethods.GroupMethods" 3 "Thu May 2 2013" "Version v1.1.0" "Labris Wireless Access Point Controller" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src.controller.GroupMethods.GroupMethods \- 
.PP
\fBGroupMethods\fP class includes group oriented methods such group set, group unset, group show operations\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBobject\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "def \fB__init__\fP"
.br
.ti -1c
.RI "def \fBcreate\fP"
.br
.RI "\fICreate a new group with given details in inventory\&. \fP"
.ti -1c
.RI "def \fBread\fP"
.br
.RI "\fIRead group detail from Groups table by given id\&. \fP"
.ti -1c
.RI "def \fBget_group_config\fP"
.br
.RI "\fIThis method gets configuration details from config table belong to given group\&. \fP"
.ti -1c
.RI "def \fBupdate\fP"
.br
.RI "\fIUpdate the group by given id\&. \fP"
.ti -1c
.RI "def \fBset\fP"
.br
.RI "\fIThis methods handle options and connect throug group devices by given name or given id\&. \fP"
.ti -1c
.RI "def \fBunset\fP"
.br
.RI "\fIThis methods handle options and connect throug group devices by given name or given id\&. \fP"
.ti -1c
.RI "def \fBshow\fP"
.br
.RI "\fIShow methods for devices in given group id\&. \fP"
.ti -1c
.RI "def \fBexec_group\fP"
.br
.RI "\fIExecute group commands\&. \fP"
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fButils\fP"
.br
.ti -1c
.RI "\fBdatabase\fP"
.br
.ti -1c
.RI "\fBlog_database\fP"
.br
.ti -1c
.RI "\fBcommunication_interface\fP"
.br
.ti -1c
.RI "\fBscript\fP"
.br
.ti -1c
.RI "\fBcfg_device\fP"
.br
.ti -1c
.RI "\fBnow\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
\fBGroupMethods\fP class includes group oriented methods such group set, group unset, group show operations\&. 

Methods covered by \fBGroupMethods\fP and other controller methods in other might be similar each other but in deep they have their own custom attributes and variables to determine each process is focused to the target\&. 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "def src\&.controller\&.GroupMethods\&.GroupMethods\&.__init__ (self)"

.SH "Member Function Documentation"
.PP 
.SS "def src\&.controller\&.GroupMethods\&.GroupMethods\&.create (self, params)"

.PP
Create a new group with given details in inventory\&. \fBParameters:\fP
.RS 4
\fIparams\fP 
.RE
.PP

.SS "def src\&.controller\&.GroupMethods\&.GroupMethods\&.exec_group (self, params)"

.PP
Execute group commands\&. \fBParameters:\fP
.RS 4
\fIparams\fP gathered params by command line arguments 
.RE
.PP
\fBReturns:\fP
.RS 4
.RE
.PP

.SS "def src\&.controller\&.GroupMethods\&.GroupMethods\&.get_group_config (self, group_id)"

.PP
This method gets configuration details from config table belong to given group\&. \fBParameters:\fP
.RS 4
\fIgroup_id\fP 
.RE
.PP

.SS "def src\&.controller\&.GroupMethods\&.GroupMethods\&.read (self, group_id)"

.PP
Read group detail from Groups table by given id\&. \fBParameters:\fP
.RS 4
\fIgroup_id\fP 
.RE
.PP

.SS "def src\&.controller\&.GroupMethods\&.GroupMethods\&.set (self, params)"

.PP
This methods handle options and connect throug group devices by given name or given id\&. Sample command: set -t group -o ssid -i [GROUPID] 
.PP
\fBParameters:\fP
.RS 4
\fIparams\fP 
.RE
.PP

.SS "def src\&.controller\&.GroupMethods\&.GroupMethods\&.show (self, params)"

.PP
Show methods for devices in given group id\&. \fBParameters:\fP
.RS 4
\fIparams\fP 
.RE
.PP

.SS "def src\&.controller\&.GroupMethods\&.GroupMethods\&.unset (self, params)"

.PP
This methods handle options and connect throug group devices by given name or given id\&. Sample command: set -t group -o ssid -i [GROUPID] 
.PP
\fBParameters:\fP
.RS 4
\fIparams\fP 
.RE
.PP

.SS "def src\&.controller\&.GroupMethods\&.GroupMethods\&.update (self, params)"

.PP
Update the group by given id\&. \fBParameters:\fP
.RS 4
\fIparams\fP 
.RE
.PP

.SH "Member Data Documentation"
.PP 
.SS "src\&.controller\&.GroupMethods\&.GroupMethods\&.cfg_device"

.SS "src\&.controller\&.GroupMethods\&.GroupMethods\&.communication_interface"

.SS "src\&.controller\&.GroupMethods\&.GroupMethods\&.database"

.SS "src\&.controller\&.GroupMethods\&.GroupMethods\&.log_database"

.SS "src\&.controller\&.GroupMethods\&.GroupMethods\&.now"

.SS "src\&.controller\&.GroupMethods\&.GroupMethods\&.script"

.SS "src\&.controller\&.GroupMethods\&.GroupMethods\&.utils"


.SH "Author"
.PP 
Generated automatically by Doxygen for Labris Wireless Access Point Controller from the source code\&.
