.TH "src.controller.main" 3 "Thu Apr 25 2013" "Version v1.1.0" "Labris Wireless Access Point Controller" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src.controller.main \- 
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBMain\fP"
.br
.RI "\fI\fBMain\fP class handles main requires and distribute them into related subprocesses\&. \fP"
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "string \fB__author__\fP = 'fatih'"
.br
.in -1c
.SH "Variable Documentation"
.PP 
.SS "string src\&.controller\&.main\&.__author__ = 'fatih'"

.SH "Author"
.PP 
Generated automatically by Doxygen for Labris Wireless Access Point Controller from the source code\&.
