.TH "src.model" 3 "Thu May 2 2013" "Version v1.1.0" "Labris Wireless Access Point Controller" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src.model \- 
.SH SYNOPSIS
.br
.PP
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBCommands\fP"
.br
.ti -1c
.RI "namespace \fBConfig\fP"
.br
.ti -1c
.RI "namespace \fBDevice\fP"
.br
.ti -1c
.RI "namespace \fBGroup\fP"
.br
.ti -1c
.RI "namespace \fBLog\fP"
.br
.ti -1c
.RI "namespace \fBRequest\fP"
.br
.ti -1c
.RI "namespace \fBVLan\fP"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "string \fB__author__\fP = 'fatih'"
.br
.in -1c
.SH "Variable Documentation"
.PP 
.SS "string src\&.model\&.__author__ = 'fatih'"

.SH "Author"
.PP 
Generated automatically by Doxygen for Labris Wireless Access Point Controller from the source code\&.
