.TH "src.model.Device.Device" 3 "Thu Mar 21 2013" "Version v1.0" "Labris Wireless Access Point Controller" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src.model.Device.Device \- 
.PP
\fBDevice\fP object class to create a runtime instance while adding a new device\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBdict\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "def \fB__init__\fP"
.br
.ti -1c
.RI "def \fBset_id\fP"
.br
.RI "\fI:param dID: \fP"
.ti -1c
.RI "def \fBget_id\fP"
.br
.RI "\fI:return: \fP"
.ti -1c
.RI "def \fBset_ip\fP"
.br
.RI "\fI:param ip: \fP"
.ti -1c
.RI "def \fBget_ip\fP"
.br
.RI "\fI:return: \fP"
.ti -1c
.RI "def \fBset_username\fP"
.br
.RI "\fI:param username: \fP"
.ti -1c
.RI "def \fBget_username\fP"
.br
.RI "\fI:return: \fP"
.ti -1c
.RI "def \fBset_password\fP"
.br
.RI "\fI:param password: \fP"
.ti -1c
.RI "def \fBget_password\fP"
.br
.RI "\fI:return: \fP"
.ti -1c
.RI "def \fBset_brand\fP"
.br
.RI "\fI:param brand: \fP"
.ti -1c
.RI "def \fBget_brand\fP"
.br
.RI "\fI:return: \fP"
.ti -1c
.RI "def \fBset_model\fP"
.br
.RI "\fI:param model: \fP"
.ti -1c
.RI "def \fBget_model\fP"
.br
.RI "\fI:return: \fP"
.ti -1c
.RI "def \fBset_firmware\fP"
.br
.RI "\fI:param firmware: \fP"
.ti -1c
.RI "def \fBget_firmware\fP"
.br
.RI "\fI:return: \fP"
.ti -1c
.RI "def \fBset_relation\fP"
.br
.RI "\fI:param relation: \fP"
.ti -1c
.RI "def \fBget_relation\fP"
.br
.RI "\fI:return: \fP"
.ti -1c
.RI "def \fBset_name\fP"
.br
.RI "\fI:param name: \fP"
.ti -1c
.RI "def \fBget_name\fP"
.br
.RI "\fI:return: \fP"
.ti -1c
.RI "def \fBset_description\fP"
.br
.RI "\fI:param description: \fP"
.ti -1c
.RI "def \fBget_description\fP"
.br
.RI "\fI:return: \fP"
.ti -1c
.RI "def \fBset_config_id\fP"
.br
.RI "\fI:param config: \fP"
.ti -1c
.RI "def \fBget_config_id\fP"
.br
.RI "\fI:return: \fP"
.ti -1c
.RI "def \fBset_config\fP"
.br
.RI "\fI:param config: \fP"
.ti -1c
.RI "def \fBget_config\fP"
.br
.RI "\fI:return: \fP"
.ti -1c
.RI "def \fBset_date_add\fP"
.br
.RI "\fI:param date: \fP"
.ti -1c
.RI "def \fBget_date_add\fP"
.br
.RI "\fI:return: \fP"
.ti -1c
.RI "def \fBset_date_modified\fP"
.br
.RI "\fI:param date: \fP"
.ti -1c
.RI "def \fBget_date_modified\fP"
.br
.RI "\fI:return: \fP"
.in -1c
.SH "Detailed Description"
.PP 
\fBDevice\fP object class to create a runtime instance while adding a new device\&. 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "def src\&.model\&.Device\&.Device\&.__init__ (self)"

.SH "Member Function Documentation"
.PP 
.SS "def src\&.model\&.Device\&.Device\&.get_brand (self)"

.PP
:return: 
.SS "def src\&.model\&.Device\&.Device\&.get_config (self)"

.PP
:return: 
.SS "def src\&.model\&.Device\&.Device\&.get_config_id (self)"

.PP
:return: 
.SS "def src\&.model\&.Device\&.Device\&.get_date_add (self)"

.PP
:return: 
.SS "def src\&.model\&.Device\&.Device\&.get_date_modified (self)"

.PP
:return: 
.SS "def src\&.model\&.Device\&.Device\&.get_description (self)"

.PP
:return: 
.SS "def src\&.model\&.Device\&.Device\&.get_firmware (self)"

.PP
:return: 
.SS "def src\&.model\&.Device\&.Device\&.get_id (self)"

.PP
:return: 
.SS "def src\&.model\&.Device\&.Device\&.get_ip (self)"

.PP
:return: 
.SS "def src\&.model\&.Device\&.Device\&.get_model (self)"

.PP
:return: 
.SS "def src\&.model\&.Device\&.Device\&.get_name (self)"

.PP
:return: 
.SS "def src\&.model\&.Device\&.Device\&.get_password (self)"

.PP
:return: 
.SS "def src\&.model\&.Device\&.Device\&.get_relation (self)"

.PP
:return: 
.SS "def src\&.model\&.Device\&.Device\&.get_username (self)"

.PP
:return: 
.SS "def src\&.model\&.Device\&.Device\&.set_brand (self, brand)"

.PP
:param brand: 
.SS "def src\&.model\&.Device\&.Device\&.set_config (self, config)"

.PP
:param config: 
.SS "def src\&.model\&.Device\&.Device\&.set_config_id (self, config)"

.PP
:param config: 
.SS "def src\&.model\&.Device\&.Device\&.set_date_add (self, date)"

.PP
:param date: 
.SS "def src\&.model\&.Device\&.Device\&.set_date_modified (self, date)"

.PP
:param date: 
.SS "def src\&.model\&.Device\&.Device\&.set_description (self, description)"

.PP
:param description: 
.SS "def src\&.model\&.Device\&.Device\&.set_firmware (self, firmware)"

.PP
:param firmware: 
.SS "def src\&.model\&.Device\&.Device\&.set_id (self, dID)"

.PP
:param dID: 
.SS "def src\&.model\&.Device\&.Device\&.set_ip (self, ip)"

.PP
:param ip: 
.SS "def src\&.model\&.Device\&.Device\&.set_model (self, model)"

.PP
:param model: 
.SS "def src\&.model\&.Device\&.Device\&.set_name (self, name)"

.PP
:param name: 
.SS "def src\&.model\&.Device\&.Device\&.set_password (self, password)"

.PP
:param password: 
.SS "def src\&.model\&.Device\&.Device\&.set_relation (self, relation)"

.PP
:param relation: 
.SS "def src\&.model\&.Device\&.Device\&.set_username (self, username)"

.PP
:param username: 

.SH "Author"
.PP 
Generated automatically by Doxygen for Labris Wireless Access Point Controller from the source code\&.
