.TH "src.controller" 3 "Thu May 2 2013" "Version v1.1.0" "Labris Wireless Access Point Controller" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src.controller \- 
.SH SYNOPSIS
.br
.PP
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBConfigMethods\fP"
.br
.ti -1c
.RI "namespace \fBDaemon\fP"
.br
.ti -1c
.RI "namespace \fBDeviceMethods\fP"
.br
.ti -1c
.RI "namespace \fBGroupMethods\fP"
.br
.ti -1c
.RI "namespace \fBLogger\fP"
.br
.ti -1c
.RI "namespace \fBmain\fP"
.br
.ti -1c
.RI "namespace \fBVLanMethods\fP"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "string \fB__author__\fP = 'fatih'"
.br
.in -1c
.SH "Variable Documentation"
.PP 
.SS "string src\&.controller\&.__author__ = 'fatih'"

.SH "Author"
.PP 
Generated automatically by Doxygen for Labris Wireless Access Point Controller from the source code\&.
