.TH "src.language.Language" 3 "Thu Apr 25 2013" "Version v1.1.0" "Labris Wireless Access Point Controller" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src.language.Language \- 
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBLanguage\fP"
.br
.RI "\fI\fBLanguage\fP class aims to provide required statement to requester class or methods to read matching locale string with given language code\&. \fP"
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Labris Wireless Access Point Controller from the source code\&.
