.TH "src.controller.VLanMethods.VLanMethods" 3 "Thu Mar 21 2013" "Version v1.0" "Labris Wireless Access Point Controller" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src.controller.VLanMethods.VLanMethods \- 
.PP
VLan methods\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits Thread\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "def \fB__init__\fP"
.br
.ti -1c
.RI "def \fBcreate\fP"
.br
.RI "\fI.PP
.nf
Add function to implement a thread at background responds to Web or CLI request
.fi
.PP
 :param params: \fP"
.ti -1c
.RI "def \fBread\fP"
.br
.RI "\fI:param vid: \fP"
.ti -1c
.RI "def \fBupdate\fP"
.br
.RI "\fI:param params: \fP"
.ti -1c
.RI "def \fBdelete\fP"
.br
.RI "\fI:param params: \fP"
.ti -1c
.RI "def \fBset\fP"
.br
.RI "\fI.PP
.nf
This methods handle options and connect throug device by given name
.fi
.PP
 :param params: \fP"
.ti -1c
.RI "def \fBgroup\fP"
.br
.RI "\fIThis methods groups given device id\&. \fP"
.ti -1c
.RI "def \fBshow\fP"
.br
.RI "\fI:param params: \fP"
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fButils\fP"
.br
.ti -1c
.RI "\fBdb\fP"
.br
.ti -1c
.RI "\fBci\fP"
.br
.ti -1c
.RI "\fBscript\fP"
.br
.ti -1c
.RI "\fBcfg_device\fP"
.br
.ti -1c
.RI "\fBnow\fP"
.br
.ti -1c
.RI "\fBdevice\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
VLan methods\&. 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "def src\&.controller\&.VLanMethods\&.VLanMethods\&.__init__ (self)"

.SH "Member Function Documentation"
.PP 
.SS "def src\&.controller\&.VLanMethods\&.VLanMethods\&.create (self, params)"

.PP
.PP
.nf
Add function to implement a thread at background responds to Web or CLI request
.fi
.PP
 :param params: 
.SS "def src\&.controller\&.VLanMethods\&.VLanMethods\&.delete (self, params)"

.PP
:param params: 
.SS "def src\&.controller\&.VLanMethods\&.VLanMethods\&.group (self, params)"

.PP
This methods groups given device id\&. Before this method to be implemented user should execute ls command to see what device(s) recorded in database\&. :param params: 
.SS "def src\&.controller\&.VLanMethods\&.VLanMethods\&.read (self, vid)"

.PP
:param vid: 
.SS "def src\&.controller\&.VLanMethods\&.VLanMethods\&.set (self, params)"

.PP
.PP
.nf
This methods handle options and connect throug device by given name
.fi
.PP
 :param params: 
.SS "def src\&.controller\&.VLanMethods\&.VLanMethods\&.show (self, params)"

.PP
:param params: 
.SS "def src\&.controller\&.VLanMethods\&.VLanMethods\&.update (self, params)"

.PP
:param params: 
.SH "Member Data Documentation"
.PP 
.SS "src\&.controller\&.VLanMethods\&.VLanMethods\&.cfg_device"

.SS "src\&.controller\&.VLanMethods\&.VLanMethods\&.ci"

.SS "src\&.controller\&.VLanMethods\&.VLanMethods\&.db"

.SS "src\&.controller\&.VLanMethods\&.VLanMethods\&.device"

.SS "src\&.controller\&.VLanMethods\&.VLanMethods\&.now"

.SS "src\&.controller\&.VLanMethods\&.VLanMethods\&.script"

.SS "src\&.controller\&.VLanMethods\&.VLanMethods\&.utils"


.SH "Author"
.PP 
Generated automatically by Doxygen for Labris Wireless Access Point Controller from the source code\&.
