.TH "src.database.CouchDriver" 3 "Thu May 2 2013" "Version v1.1.0" "Labris Wireless Access Point Controller" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src.database.CouchDriver \- 
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBCouchDriver\fP"
.br
.RI "\fI\fBCouchDriver\fP class implement a database interface between application database class and CouchDB\&. \fP"
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "string \fB__author__\fP = 'fatih'"
.br
.in -1c
.SH "Variable Documentation"
.PP 
.SS "string src\&.database\&.CouchDriver\&.__author__ = 'fatih'"

.SH "Author"
.PP 
Generated automatically by Doxygen for Labris Wireless Access Point Controller from the source code\&.
