.TH "src.controller.Logger.Logger" 3 "Thu Apr 25 2013" "Version v1.1.0" "Labris Wireless Access Point Controller" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src.controller.Logger.Logger \- 
.PP
\fBLogger\fP class is an logging implementation uses CouchDB to record logs\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits logging\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "def \fB__init__\fP"
.br
.RI "\fI\fBLogger\fP initializer\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 
\fBLogger\fP class is an logging implementation uses CouchDB to record logs\&. 

Log types debug, info, warning, error and critical\&. Please see further details at http://docs.python.org/2/howto/logging.html#logging-basic-tutorial 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "def src\&.controller\&.Logger\&.Logger\&.__init__ (self)"

.PP
\fBLogger\fP initializer\&. \fBReturns:\fP
.RS 4
: 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for Labris Wireless Access Point Controller from the source code\&.
