.TH "src.controller.Logger.Logger" 3 "Thu May 2 2013" "Version v1.1.0" "Labris Wireless Access Point Controller" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src.controller.Logger.Logger \- 
.PP
\fBLogger\fP class is an logging implementation uses CouchDB to record logs\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBgetLoggerClass\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "def \fB__init__\fP"
.br
.RI "\fI\fBLogger\fP initializer\&. \fP"
.ti -1c
.RI "def \fBcreate_log\fP"
.br
.RI "\fICreate Log by given parameters\&. \fP"
.ti -1c
.RI "def \fBgather_logs\fP"
.br
.RI "\fIGather logs by given params\&. \fP"
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fButils\fP"
.br
.ti -1c
.RI "\fBdatabase\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
\fBLogger\fP class is an logging implementation uses CouchDB to record logs\&. 

Log types debug, info, warning, error and critical\&. Please see further details at http://docs.python.org/2/howto/logging.html#logging-basic-tutorial 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "def src\&.controller\&.Logger\&.Logger\&.__init__ (self)"

.PP
\fBLogger\fP initializer\&. \fBReturns:\fP
.RS 4
: 
.RE
.PP

.SH "Member Function Documentation"
.PP 
.SS "def src\&.controller\&.Logger\&.Logger\&.create_log (self, name, severity, line, message, method, facility, host)"

.PP
Create Log by given parameters\&. \fBParameters:\fP
.RS 4
\fIname\fP 
.br
\fIseverity\fP 
.br
\fIline\fP 
.br
\fImessage\fP 
.br
\fImethod\fP 
.br
\fIfacility\fP 
.br
\fIhost\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
log id gathered from log database 
.RE
.PP

.SS "def src\&.controller\&.Logger\&.Logger\&.gather_logs (self, params, opt = \fC'_all_docs'\fP)"

.PP
Gather logs by given params\&. \fBParameters:\fP
.RS 4
\fIparams\fP to create query by given dict objects 
.br
\fIopt\fP to define which log documents will be gathered 
.RE
.PP
\fBReturns:\fP
.RS 4
: 
.RE
.PP

.SH "Member Data Documentation"
.PP 
.SS "src\&.controller\&.Logger\&.Logger\&.database"

.SS "src\&.controller\&.Logger\&.Logger\&.utils"


.SH "Author"
.PP 
Generated automatically by Doxygen for Labris Wireless Access Point Controller from the source code\&.
