.TH "src.model.Request" 3 "Thu Mar 28 2013" "Version v1.0" "Labris Wireless Access Point Controller" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src.model.Request \- 
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBRequest\fP"
.br
.RI "\fI\fBRequest\fP object class to generate a new request 'enable':true, 'configure':false, 'commands':[ { 'command':'showa dot11 bssid' } ]\&. \fP"
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Labris Wireless Access Point Controller from the source code\&.
