.TH "src.helpers.Utils.Utils" 3 "Thu Apr 25 2013" "Version v1.1.0" "Labris Wireless Access Point Controller" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src.helpers.Utils.Utils \- 
.PP
\fBUtils\fP class implements utility methods to help core methods work fine, independent, reliable and effective\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBobject\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "def \fB__init__\fP"
.br
.ti -1c
.RI "def \fBinit_globals\fP"
.br
.ti -1c
.RI "def \fBget_clean_params\fP"
.br
.RI "\fIget_clean_params method return filtered and processed arguments gathered from command line into argument parser\&. \fP"
.ti -1c
.RI "def \fBformatter\fP"
.br
.RI "\fIFormat output text as a human readable style\&. \fP"
.ti -1c
.RI "def \fBget_line\fP"
.br
.RI "\fIGet current line of file to handle exception lines\&. \fP"
.ti -1c
.RI "def \fBvalidate\fP"
.br
.RI "\fIThis method is used to validate given input source by type format such as IP, email, whitespace-free strings, etc\&. \fP"
.ti -1c
.RI "def \fBfix_date\fP"
.br
.RI "\fIThis method aims to fix date format gathered from database\&. \fP"
.ti -1c
.RI "def \fBwellform_dict\fP"
.br
.RI "\fIThis method aims to wellform the given source into a zipped dictionary from keys and values\&. \fP"
.ti -1c
.RI "def \fBget_request_config\fP"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "\fBnow\fP = None"
.br
.ti -1c
.RI "\fBenvironment\fP = None"
.br
.ti -1c
.RI "\fBpostfix\fP = None"
.br
.in -1c
.SH "Detailed Description"
.PP 
\fBUtils\fP class implements utility methods to help core methods work fine, independent, reliable and effective\&. 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "def src\&.helpers\&.Utils\&.Utils\&.__init__ (self)"

.SH "Member Function Documentation"
.PP 
.SS "def src\&.helpers\&.Utils\&.Utils\&.fix_date (cls, source)"

.PP
This method aims to fix date format gathered from database\&. Database record comes from datetime\&.datetime formatted and this makes operations fails because of malformed data\&. So, it should be formatted to the regular datetime format\&.
.PP
\fBParameters:\fP
.RS 4
\fIcls\fP 
.br
\fIsource\fP is a dictionary 
.RE
.PP
\fBReturns:\fP
.RS 4
formatted dictionary 
.RE
.PP

.SS "def src\&.helpers\&.Utils\&.Utils\&.formatter (cls, heading, source)"

.PP
Format output text as a human readable style\&. \fBParameters:\fP
.RS 4
\fIcls\fP is class itself 
.br
\fIheading\fP is a list object comes from other methods to create a pretty table to be printed
.br
\fIsource\fP is a tuple list aims to create pretty table rows 
.RE
.PP

.SS "def src\&.helpers\&.Utils\&.Utils\&.get_clean_params (cls, args)"

.PP
get_clean_params method return filtered and processed arguments gathered from command line into argument parser\&. Arguments retrieved with whitespaces, irregular order and mapped\&. Therefore it is need to be cleaned, reorganized and regularly mapped to send correct values into argument parser\&. This method help us to clean and get actual ordered parameters as a list\&.
.PP
\fBParameters:\fP
.RS 4
\fIcls\fP class itself 
.br
\fIargs\fP arguments list gathered from command line 
.RE
.PP
\fBReturns:\fP
.RS 4
A fully organized and clean argument list 
.RE
.PP

.SS "def src\&.helpers\&.Utils\&.Utils\&.get_line (cls)"

.PP
Get current line of file to handle exception lines\&. \fBParameters:\fP
.RS 4
\fIcls\fP class itself
.RE
.PP
\fBReturns:\fP
.RS 4
Current number of line where method is called 
.RE
.PP

.SS "def src\&.helpers\&.Utils\&.Utils\&.get_request_config (self, device = \fC\fBDevice\fP()\fP, config = \fC\fBConfig\fP()\fP)"
\fBParameters:\fP
.RS 4
\fIdevice\fP 
.br
\fIconfig\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
target file to implement in perl script 
.RE
.PP

.SS "def src\&.helpers\&.Utils\&.Utils\&.init_globals (self)"
\fBReturns:\fP
.RS 4
.RE
.PP

.SS "def src\&.helpers\&.Utils\&.Utils\&.validate (cls, source = \fCNone\fP, stype = \fCNone\fP)"

.PP
This method is used to validate given input source by type format such as IP, email, whitespace-free strings, etc\&. \fBParameters:\fP
.RS 4
\fIcls\fP class itself
.br
\fItype\fP defines what sort of value will be validated\&. Recently supported keys name, eth & ip
.br
\fIsource\fP 
.RE
.PP

.SS "def src\&.helpers\&.Utils\&.Utils\&.wellform_dict (cls, source, keys, values)"

.PP
This method aims to wellform the given source into a zipped dictionary from keys and values\&. \fBParameters:\fP
.RS 4
\fIcls\fP 
.br
\fIsource\fP dictionary source 
.br
\fIkeys\fP will be keys of new dictionary 
.br
\fIvalues\fP will be values for regarding keys 
.RE
.PP
\fBReturns:\fP
.RS 4
.RE
.PP

.SH "Member Data Documentation"
.PP 
.SS "src\&.helpers\&.Utils\&.Utils\&.environment = None\fC [static]\fP"

.SS "src\&.helpers\&.Utils\&.Utils\&.now = None\fC [static]\fP"

.SS "src\&.helpers\&.Utils\&.Utils\&.postfix = None\fC [static]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for Labris Wireless Access Point Controller from the source code\&.
