.TH "src.model.Response.Response" 3 "Thu Mar 21 2013" "Version v1.0" "Labris Wireless Access Point Controller" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src.model.Response.Response \- 
.PP
\fBResponse\fP is a class to handle the CI response\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBdict\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "def \fBsetStatus\fP"
.br
.RI "\fI:param status: \fP"
.ti -1c
.RI "def \fBgetStatus\fP"
.br
.RI "\fI:return: \fP"
.ti -1c
.RI "def \fBsetMessage\fP"
.br
.RI "\fI:param message: \fP"
.ti -1c
.RI "def \fBgetMessage\fP"
.br
.RI "\fI:return: \fP"
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "\fBstatus\fP = None"
.br
.ti -1c
.RI "\fBmessage\fP = None"
.br
.in -1c
.SH "Detailed Description"
.PP 
\fBResponse\fP is a class to handle the CI response\&. 
.SH "Member Function Documentation"
.PP 
.SS "def src\&.model\&.Response\&.Response\&.getMessage (self)"

.PP
:return: 
.SS "def src\&.model\&.Response\&.Response\&.getStatus (self)"

.PP
:return: 
.SS "def src\&.model\&.Response\&.Response\&.setMessage (self, message)"

.PP
:param message: 
.SS "def src\&.model\&.Response\&.Response\&.setStatus (self, status)"

.PP
:param status: 
.SH "Member Data Documentation"
.PP 
.SS "src\&.model\&.Response\&.Response\&.message = None\fC [static]\fP"

.SS "src\&.model\&.Response\&.Response\&.status = None\fC [static]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for Labris Wireless Access Point Controller from the source code\&.
