.TH "src.model.Request.Request" 3 "Tue Mar 26 2013" "Version v1.0" "Labris Wireless Access Point Controller" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src.model.Request.Request \- 
.PP
\fBRequest\fP object class to generate a new request 'enable':true, 'configure':false, 'commands':[ { 'command':'showa dot11 bssid' } ]\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBdict\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "def \fB__init__\fP"
.br
.RI "\fIConstructer for \fBRequest\fP model\&. \fP"
.ti -1c
.RI "def \fBset_enable\fP"
.br
.RI "\fISetter for enable variable\&. \fP"
.ti -1c
.RI "def \fBget_enable\fP"
.br
.RI "\fIGetter for enable variable\&. \fP"
.ti -1c
.RI "def \fBset_configure\fP"
.br
.RI "\fISetter for configure variable\&. \fP"
.ti -1c
.RI "def \fBget_configure\fP"
.br
.RI "\fIGetter for configure variable\&. \fP"
.ti -1c
.RI "def \fBset_commands\fP"
.br
.RI "\fISetter for commands\&. \fP"
.ti -1c
.RI "def \fBget_commands\fP"
.br
.RI "\fIGetter for \fBCommands\fP\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 
\fBRequest\fP object class to generate a new request 'enable':true, 'configure':false, 'commands':[ { 'command':'showa dot11 bssid' } ]\&. 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "def src\&.model\&.Request\&.Request\&.__init__ (self)"

.PP
Constructer for \fBRequest\fP model\&. 
.SH "Member Function Documentation"
.PP 
.SS "def src\&.model\&.Request\&.Request\&.get_commands (self)"

.PP
Getter for \fBCommands\fP\&. \fBReturns:\fP
.RS 4
instance \fBCommands\fP model 
.RE
.PP

.SS "def src\&.model\&.Request\&.Request\&.get_configure (self)"

.PP
Getter for configure variable\&. \fBReturns:\fP
.RS 4
configure true or false 
.RE
.PP

.SS "def src\&.model\&.Request\&.Request\&.get_enable (self)"

.PP
Getter for enable variable\&. \fBReturns:\fP
.RS 4
enable true or false 
.RE
.PP

.SS "def src\&.model\&.Request\&.Request\&.set_commands (self, commands)"

.PP
Setter for commands\&. .PP
.nf
     This method set Commands model provided by other methods to Request
     object
.fi
.PP
.PP
\fBParameters:\fP
.RS 4
\fIcommands\fP \fBCommands\fP model 
.RE
.PP

.SS "def src\&.model\&.Request\&.Request\&.set_configure (self, status)"

.PP
Setter for configure variable\&. .PP
.nf
     Configure variable required by devices to let the user make
     configuration(s) on the device.
.fi
.PP
.PP
\fBParameters:\fP
.RS 4
\fIstatus\fP true or false 
.RE
.PP

.SS "def src\&.model\&.Request\&.Request\&.set_enable (self, status)"

.PP
Setter for enable variable\&. .PP
.nf
     Enable variable required by devices to enable configuration mode true
     or false and then device decides to let the user make configuration(s)
     on the device.
.fi
.PP
.PP
\fBParameters:\fP
.RS 4
\fIstatus\fP true or false 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for Labris Wireless Access Point Controller from the source code\&.
