.TH "src.model.Request.Request" 3 "Thu Mar 21 2013" "Version v1.0" "Labris Wireless Access Point Controller" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src.model.Request.Request \- 
.PP
\fBRequest\fP object class to generate a new request 'enable':true, 'configure':false, 'commands':[ { 'command':'showa dot11 bssid' } ]\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBdict\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "def \fB__init__\fP"
.br
.ti -1c
.RI "def \fBsetEnable\fP"
.br
.RI "\fI:param status: \fP"
.ti -1c
.RI "def \fBgetEnable\fP"
.br
.RI "\fI:return: \fP"
.ti -1c
.RI "def \fBsetConfigure\fP"
.br
.RI "\fI:param status: \fP"
.ti -1c
.RI "def \fBgetConfigure\fP"
.br
.RI "\fI:return: \fP"
.ti -1c
.RI "def \fBsetCommands\fP"
.br
.RI "\fI:param commands: \fP"
.ti -1c
.RI "def \fBgetCommands\fP"
.br
.RI "\fI:return: \fP"
.ti -1c
.RI "def \fBaddCommand\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
\fBRequest\fP object class to generate a new request 'enable':true, 'configure':false, 'commands':[ { 'command':'showa dot11 bssid' } ]\&. 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "def src\&.model\&.Request\&.Request\&.__init__ (self)"

.SH "Member Function Documentation"
.PP 
.SS "def src\&.model\&.Request\&.Request\&.addCommand (self, command)"

.SS "def src\&.model\&.Request\&.Request\&.getCommands (self)"

.PP
:return: 
.SS "def src\&.model\&.Request\&.Request\&.getConfigure (self)"

.PP
:return: 
.SS "def src\&.model\&.Request\&.Request\&.getEnable (self)"

.PP
:return: 
.SS "def src\&.model\&.Request\&.Request\&.setCommands (self, commands)"

.PP
:param commands: 
.SS "def src\&.model\&.Request\&.Request\&.setConfigure (self, status)"

.PP
:param status: 
.SS "def src\&.model\&.Request\&.Request\&.setEnable (self, status)"

.PP
:param status: 

.SH "Author"
.PP 
Generated automatically by Doxygen for Labris Wireless Access Point Controller from the source code\&.
