.TH "src.model.Group" 3 "Thu Mar 21 2013" "Version v1.0" "Labris Wireless Access Point Controller" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src.model.Group \- 
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBGroup\fP"
.br
.RI "\fI\fBGroup\fP class to create a runtime instance while adding a new device\&. \fP"
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "string \fB__author__\fP = 'fatih'"
.br
.RI "\fI\fBGroup\fP model for create group instance determine database column field\&. \fP"
.in -1c
.SH "Variable Documentation"
.PP 
.SS "string src\&.model\&.Group\&.__author__ = 'fatih'"

.PP
\fBGroup\fP model for create group instance determine database column field\&. 
.SH "Author"
.PP 
Generated automatically by Doxygen for Labris Wireless Access Point Controller from the source code\&.
