.TH "src.model.Group.Group" 3 "Tue Mar 26 2013" "Version v1.0" "Labris Wireless Access Point Controller" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src.model.Group.Group \- 
.PP
\fBGroup\fP class to create a runtime instance while adding a new device\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBsrc\&.model\&.Device\&.Device\fP, and \fBsrc\&.model\&.Device\&.Device\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "def \fB__init__\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
\fBGroup\fP class to create a runtime instance while adding a new device\&. 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "def src\&.model\&.Group\&.Group\&.__init__ (self)"


.SH "Author"
.PP 
Generated automatically by Doxygen for Labris Wireless Access Point Controller from the source code\&.
