.TH "src.database.PostgreDriver" 3 "Thu Apr 25 2013" "Version v1.1.0" "Labris Wireless Access Point Controller" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src.database.PostgreDriver \- 
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBPostgreDriver\fP"
.br
.RI "\fI\fBPostgreDriver\fP class implement a database interface between application database class and postgresql\&. \fP"
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "string \fB__author__\fP = 'fatih'"
.br
.in -1c
.SH "Variable Documentation"
.PP 
.SS "string src\&.database\&.PostgreDriver\&.__author__ = 'fatih'"

.SH "Author"
.PP 
Generated automatically by Doxygen for Labris Wireless Access Point Controller from the source code\&.
