.TH "src.controller.ConfigMethods.ConfigMethods" 3 "Thu May 2 2013" "Version v1.1.0" "Labris Wireless Access Point Controller" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src.controller.ConfigMethods.ConfigMethods \- 
.PP
\fBConfigMethods\fP class aims to provide required methods to requester class or methods to read, update Config object\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBThread\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "def \fB__init__\fP"
.br
.RI "\fIConstructor of \fBConfigMethods\fP\&. \fP"
.ti -1c
.RI "def \fBcreate\fP"
.br
.RI "\fIThis method is used to create a config independently\&. \fP"
.ti -1c
.RI "def \fBread\fP"
.br
.RI "\fIread method aims to read given config id details from database and return them into a result set list\&. \fP"
.ti -1c
.RI "def \fBset\fP"
.br
.RI "\fISet method will update given config by parameter\&. \fP"
.ti -1c
.RI "def \fBupdate\fP"
.br
.RI "\fIUpdate methods certainly moderated by $ edit [OPTIONS] command by CLI\&. \fP"
.ti -1c
.RI "def \fBdelete\fP"
.br
.RI "\fI:param params: \fP"
.ti -1c
.RI "def \fBshow\fP"
.br
.RI "\fI:param params: \fP"
.ti -1c
.RI "def \fBset_config\fP"
.br
.RI "\fI\fBConfigMethods\fP controller class config setter\&. \fP"
.ti -1c
.RI "def \fBget_config\fP"
.br
.RI "\fI\fBConfigMethods\fP controller class config getter\&. \fP"
.ti -1c
.RI "def \fBset_params\fP"
.br
.RI "\fI\fBConfigMethods\fP controller class config setter\&. \fP"
.ti -1c
.RI "def \fBget_params\fP"
.br
.RI "\fI\fBConfigMethods\fP controller class config getter\&. \fP"
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fButils\fP"
.br
.ti -1c
.RI "\fBdatabase\fP"
.br
.ti -1c
.RI "\fBlog_database\fP"
.br
.ti -1c
.RI "\fBcommunication_interface\fP"
.br
.ti -1c
.RI "\fBscript\fP"
.br
.ti -1c
.RI "\fBcfg_device\fP"
.br
.ti -1c
.RI "\fBnow\fP"
.br
.ti -1c
.RI "\fBconfig\fP"
.br
.ti -1c
.RI "\fBparams\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
\fBConfigMethods\fP class aims to provide required methods to requester class or methods to read, update Config object\&. 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "def src\&.controller\&.ConfigMethods\&.ConfigMethods\&.__init__ (self, new_config, params)"

.PP
Constructor of \fBConfigMethods\fP\&. \fBParameters:\fP
.RS 4
\fInew_config\fP Is a new config tuple object to update self\&.config 
.br
\fIparams\fP Is used to set new parameters to recent instance 
.RE
.PP

.SH "Member Function Documentation"
.PP 
.SS "def src\&.controller\&.ConfigMethods\&.ConfigMethods\&.create (self, params)"

.PP
This method is used to create a config independently\&. \fBParameters:\fP
.RS 4
\fIparams\fP 
.RE
.PP

.SS "def src\&.controller\&.ConfigMethods\&.ConfigMethods\&.delete (self, params)"

.PP
:param params: 
.SS "def src\&.controller\&.ConfigMethods\&.ConfigMethods\&.get_config (self)"

.PP
\fBConfigMethods\fP controller class config getter\&. \fBReturns:\fP
.RS 4
config is a Config object 
.RE
.PP

.SS "def src\&.controller\&.ConfigMethods\&.ConfigMethods\&.get_params (self)"

.PP
\fBConfigMethods\fP controller class config getter\&. \fBReturns:\fP
.RS 4
params is a Config object 
.RE
.PP

.SS "def src\&.controller\&.ConfigMethods\&.ConfigMethods\&.read (self, config_id)"

.PP
read method aims to read given config id details from database and return them into a result set list\&. \fBParameters:\fP
.RS 4
\fIconfig_id\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
result set list includes column names and rows 
.RE
.PP

.SS "def src\&.controller\&.ConfigMethods\&.ConfigMethods\&.set (self, config)"

.PP
Set method will update given config by parameter\&. \fBParameters:\fP
.RS 4
\fIconfig\fP is a Config model which provided by parameter 
.RE
.PP

.SS "def src\&.controller\&.ConfigMethods\&.ConfigMethods\&.set_config (self, config)"

.PP
\fBConfigMethods\fP controller class config setter\&. \fBParameters:\fP
.RS 4
\fIconfig\fP is a Config object includes details 
.RE
.PP

.SS "def src\&.controller\&.ConfigMethods\&.ConfigMethods\&.set_params (self, params)"

.PP
\fBConfigMethods\fP controller class config setter\&. \fBParameters:\fP
.RS 4
\fIparams\fP is a Config object includes details 
.RE
.PP

.SS "def src\&.controller\&.ConfigMethods\&.ConfigMethods\&.show (self, params)"

.PP
:param params: 
.SS "def src\&.controller\&.ConfigMethods\&.ConfigMethods\&.update (self, params)"

.PP
Update methods certainly moderated by $ edit [OPTIONS] command by CLI\&. This methods only inherit update database records by no touching physical device config\&.
.PP
\fBParameters:\fP
.RS 4
\fIparams\fP 
.RE
.PP

.SH "Member Data Documentation"
.PP 
.SS "src\&.controller\&.ConfigMethods\&.ConfigMethods\&.cfg_device"

.SS "src\&.controller\&.ConfigMethods\&.ConfigMethods\&.communication_interface"

.SS "src\&.controller\&.ConfigMethods\&.ConfigMethods\&.config"

.SS "src\&.controller\&.ConfigMethods\&.ConfigMethods\&.database"

.SS "src\&.controller\&.ConfigMethods\&.ConfigMethods\&.log_database"

.SS "src\&.controller\&.ConfigMethods\&.ConfigMethods\&.now"

.SS "src\&.controller\&.ConfigMethods\&.ConfigMethods\&.params"

.SS "src\&.controller\&.ConfigMethods\&.ConfigMethods\&.script"

.SS "src\&.controller\&.ConfigMethods\&.ConfigMethods\&.utils"


.SH "Author"
.PP 
Generated automatically by Doxygen for Labris Wireless Access Point Controller from the source code\&.
