.TH "src.model.Device" 3 "Thu Mar 21 2013" "Version v1.0" "Labris Wireless Access Point Controller" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src.model.Device \- 
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBDevice\fP"
.br
.RI "\fI\fBDevice\fP object class to create a runtime instance while adding a new device\&. \fP"
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "string \fB__author__\fP = 'fatih'"
.br
.in -1c
.SH "Variable Documentation"
.PP 
.SS "string src\&.model\&.Device\&.__author__ = 'fatih'"

.SH "Author"
.PP 
Generated automatically by Doxygen for Labris Wireless Access Point Controller from the source code\&.
