.TH "src.controller.DeviceMethods.DeviceMethods" 3 "Thu Apr 25 2013" "Version v1.1.0" "Labris Wireless Access Point Controller" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src.controller.DeviceMethods.DeviceMethods \- 
.PP
\fBDeviceMethods\fP class includes device oriented methods such CRUD operations\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBThread\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "def \fB__init__\fP"
.br
.RI "\fIConstructor for \fBDeviceMethods\fP\&. \fP"
.ti -1c
.RI "def \fBcreate\fP"
.br
.RI "\fICreate method aims to create a new device insert it into database and apply the config regarding given brand, model and firmware\&. \fP"
.ti -1c
.RI "def \fBread\fP"
.br
.RI "\fI:param id: \fP"
.ti -1c
.RI "def \fBupdate\fP"
.br
.RI "\fIUpdate methods certainly moderated by $ edit [OPTIONS] command by CLI\&. \fP"
.ti -1c
.RI "def \fBset\fP"
.br
.RI "\fIThis methods handle options and connect through device by given name\&. \fP"
.ti -1c
.RI "def \fBshow\fP"
.br
.RI "\fIShow methods submit returns where sh commands came from\&. \fP"
.ti -1c
.RI "def \fBgroup\fP"
.br
.ti -1c
.RI "def \fBexecute_precommand\fP"
.br
.RI "\fIExecute pre-requested device commands\&. \fP"
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fButils\fP"
.br
.ti -1c
.RI "\fBdatabase\fP"
.br
.ti -1c
.RI "\fBcommunication_interface\fP"
.br
.ti -1c
.RI "\fBscript\fP"
.br
.ti -1c
.RI "\fBcfg_device\fP"
.br
.ti -1c
.RI "\fBnow\fP"
.br
.ti -1c
.RI "\fBparams\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
\fBDeviceMethods\fP class includes device oriented methods such CRUD operations\&. 

Methods covered by \fBDeviceMethods\fP and other controller methods in other might be similar each other but in deep they have their own custom attributes and variables to determine each process is focused to the target\&. 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "def src\&.controller\&.DeviceMethods\&.DeviceMethods\&.__init__ (self, params)"

.PP
Constructor for \fBDeviceMethods\fP\&. 
.SH "Member Function Documentation"
.PP 
.SS "def src\&.controller\&.DeviceMethods\&.DeviceMethods\&.create (self, params)"

.PP
Create method aims to create a new device insert it into database and apply the config regarding given brand, model and firmware\&. Create method is called by Main\&.add method by given type\&. Type should be provided as 'device'\&. Also when adding a new device arguments listed below have to be provided:
.PP
.SS "Usage: $ add [OPTIONS]"
.PP
Add device, group, vlan, config etc with given parameters 
.PD 0

.IP "\(bu" 2
[-t],[--type] Define type device, group, vlan, config 
.IP "\(bu" 2
[-I],[--ip] Use this params when adding some new variables which  needs an ip such as device, config, etc\&. 
.IP "\(bu" 2
[-n],[--name] To set a name to related type variable 
.IP "\(bu" 2
[-b],[--brand] To set device brand to relate with its model and/or  firmware 
.IP "\(bu" 2
[-m],[--model] To set device model to relate with its config file  
.IP "\(bu" 2
[-F],[--firmware] To set device firmware to relate with its config file 
.IP "\(bu" 2
[-R],[--relation] To set device relation one of MASTER of SLAVE 
.IP "\(bu" 2
[-D],[--description] To set a description to related type variable  
.IP "\(bu" 2
[-u],[--username] Provide a username which will be used to connect device 
.IP "\(bu" 2
[-p],[--password] Provide a password which will be used to connect  and configure device 
.PP
.PP
If there is no parameter provided every required parameter will be gathered by asking the user to provide every single parameter\&.
.PP
\fBParameters:\fP
.RS 4
\fIparams\fP 
.RE
.PP

.SS "def src\&.controller\&.DeviceMethods\&.DeviceMethods\&.execute_precommand (self, device, commands, config, interface, request, params, option)"

.PP
Execute pre-requested device commands\&. \fBParameters:\fP
.RS 4
\fIparams\fP 
.br
\fIoption\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
.RE
.PP

.SS "def src\&.controller\&.DeviceMethods\&.DeviceMethods\&.group (self, params, queue, config = \fC\fBConfig\fP()\fP)"

.SS "def src\&.controller\&.DeviceMethods\&.DeviceMethods\&.read (self, cid)"

.PP
:param id: 
.SS "def src\&.controller\&.DeviceMethods\&.DeviceMethods\&.set (self, params)"

.PP
This methods handle options and connect through device by given name\&. Params contains a command option either one of set or unset\&. Regarding this params\&.command option method decides what operation will be implemented\&.
.PP
\fBParameters:\fP
.RS 4
\fIparams\fP 
.RE
.PP

.SS "def src\&.controller\&.DeviceMethods\&.DeviceMethods\&.show (self, params)"

.PP
Show methods submit returns where sh commands came from\&. Show methods gathers parameter, read commands file regarding device brand, model etc and then generate a JSON file and execute this file with CommunicationInterface
.PP
\fBParameters:\fP
.RS 4
\fIparams\fP 
.RE
.PP

.SS "def src\&.controller\&.DeviceMethods\&.DeviceMethods\&.update (self, params)"

.PP
Update methods certainly moderated by $ edit [OPTIONS] command by CLI\&. This methods only inherit update database records by no touching physical device config\&.
.PP
params comes from main class 
.SH "Member Data Documentation"
.PP 
.SS "src\&.controller\&.DeviceMethods\&.DeviceMethods\&.cfg_device"

.SS "src\&.controller\&.DeviceMethods\&.DeviceMethods\&.communication_interface"

.SS "src\&.controller\&.DeviceMethods\&.DeviceMethods\&.database"

.SS "src\&.controller\&.DeviceMethods\&.DeviceMethods\&.now"

.SS "src\&.controller\&.DeviceMethods\&.DeviceMethods\&.params"

.SS "src\&.controller\&.DeviceMethods\&.DeviceMethods\&.script"

.SS "src\&.controller\&.DeviceMethods\&.DeviceMethods\&.utils"


.SH "Author"
.PP 
Generated automatically by Doxygen for Labris Wireless Access Point Controller from the source code\&.
