.TH "src.model.Group.Group" 3 "Thu Mar 21 2013" "Version v1.0" "Labris Wireless Access Point Controller" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src.model.Group.Group \- 
.PP
\fBGroup\fP class to create a runtime instance while adding a new device\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBobject\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "def \fB__init__\fP"
.br
.ti -1c
.RI "def \fBset_id\fP"
.br
.RI "\fI.PP
.nf
Regular setter for Group model id
.fi
.PP
 :param gID: \fP"
.ti -1c
.RI "def \fBget_id\fP"
.br
.RI "\fI.PP
.nf
Regular getter for Group model
.fi
.PP
 :return id: \fP"
.ti -1c
.RI "def \fBset_name\fP"
.br
.RI "\fI:param name: \fP"
.ti -1c
.RI "def \fBget_name\fP"
.br
.RI "\fI:return: \fP"
.ti -1c
.RI "def \fBset_config\fP"
.br
.RI "\fI:param config: \fP"
.ti -1c
.RI "def \fBget_config\fP"
.br
.RI "\fI:return: \fP"
.ti -1c
.RI "def \fBset_description\fP"
.br
.RI "\fI:param description: \fP"
.ti -1c
.RI "def \fBget_description\fP"
.br
.RI "\fI:return: \fP"
.ti -1c
.RI "def \fBset_date_add\fP"
.br
.RI "\fI:param date: \fP"
.ti -1c
.RI "def \fBget_date_add\fP"
.br
.RI "\fI:return: \fP"
.ti -1c
.RI "def \fBset_date_modified\fP"
.br
.RI "\fI:param date: \fP"
.ti -1c
.RI "def \fBget_date_modified\fP"
.br
.RI "\fI:return: \fP"
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBid\fP"
.br
.ti -1c
.RI "\fBname\fP"
.br
.ti -1c
.RI "\fBconfig_id\fP"
.br
.ti -1c
.RI "\fBdescription\fP"
.br
.ti -1c
.RI "\fBadded\fP"
.br
.ti -1c
.RI "\fBmodified\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
\fBGroup\fP class to create a runtime instance while adding a new device\&. 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "def src\&.model\&.Group\&.Group\&.__init__ (self)"

.SH "Member Function Documentation"
.PP 
.SS "def src\&.model\&.Group\&.Group\&.get_config (self)"

.PP
:return: 
.SS "def src\&.model\&.Group\&.Group\&.get_date_add (self)"

.PP
:return: 
.SS "def src\&.model\&.Group\&.Group\&.get_date_modified (self)"

.PP
:return: 
.SS "def src\&.model\&.Group\&.Group\&.get_description (self)"

.PP
:return: 
.SS "def src\&.model\&.Group\&.Group\&.get_id (self)"

.PP
.PP
.nf
Regular getter for Group model
.fi
.PP
 :return id: 
.SS "def src\&.model\&.Group\&.Group\&.get_name (self)"

.PP
:return: 
.SS "def src\&.model\&.Group\&.Group\&.set_config (self, config)"

.PP
:param config: 
.SS "def src\&.model\&.Group\&.Group\&.set_date_add (self, date)"

.PP
:param date: 
.SS "def src\&.model\&.Group\&.Group\&.set_date_modified (self, date)"

.PP
:param date: 
.SS "def src\&.model\&.Group\&.Group\&.set_description (self, description)"

.PP
:param description: 
.SS "def src\&.model\&.Group\&.Group\&.set_id (self, gID)"

.PP
.PP
.nf
Regular setter for Group model id
.fi
.PP
 :param gID: 
.SS "def src\&.model\&.Group\&.Group\&.set_name (self, name)"

.PP
:param name: 
.SH "Member Data Documentation"
.PP 
.SS "src\&.model\&.Group\&.Group\&.added"

.SS "src\&.model\&.Group\&.Group\&.config_id"

.SS "src\&.model\&.Group\&.Group\&.description"

.SS "src\&.model\&.Group\&.Group\&.id"

.SS "src\&.model\&.Group\&.Group\&.modified"

.SS "src\&.model\&.Group\&.Group\&.name"


.SH "Author"
.PP 
Generated automatically by Doxygen for Labris Wireless Access Point Controller from the source code\&.
