.TH "src/test/controller/test_log.py" 3 "Thu May 2 2013" "Version v1.1.0" "Labris Wireless Access Point Controller" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/test/controller/test_log.py \- 
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBsrc\&.test\&.controller\&.test_log\&.LogTestCase\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBsrc\&.test\&.controller\&.test_log\fP"
.br
.ti -1c
.RI "namespace \fBtest\fP"
.br
.RI "\fICopyright 2013 Labris Technology\&. \fP"
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "string \fBsrc\&.test\&.controller\&.test_log\&.__author__\fP = 'fatih'"
.br
.ti -1c
.RI "tuple \fBsrc\&.test\&.controller\&.test_log\&.test_logger\fP = LogTestCase()"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Labris Wireless Access Point Controller from the source code\&.
