.TH "TestCase" 3 "Thu May 2 2013" "Version v1.1.0" "Labris Wireless Access Point Controller" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TestCase \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBsrc\&.test\&.controller\&.test_log\&.LogTestCase\fP, and \fBsrc\&.test\&.controller\&.TestDeviceMethods\&.TestDeviceMethods\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Labris Wireless Access Point Controller from the source code\&.
